// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aleph/nlp/v1/nlp.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/nlp/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NLPServiceName is the fully-qualified name of the NLPService service.
	NLPServiceName = "aleph.nlp.v1.NLPService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NLPServiceAnalyzeSentimentProcedure is the fully-qualified name of the NLPService's
	// AnalyzeSentiment RPC.
	NLPServiceAnalyzeSentimentProcedure = "/aleph.nlp.v1.NLPService/AnalyzeSentiment"
	// NLPServiceStreamPredictionsProcedure is the fully-qualified name of the NLPService's
	// StreamPredictions RPC.
	NLPServiceStreamPredictionsProcedure = "/aleph.nlp.v1.NLPService/StreamPredictions"
	// NLPServiceRecordFeedbackProcedure is the fully-qualified name of the NLPService's RecordFeedback
	// RPC.
	NLPServiceRecordFeedbackProcedure = "/aleph.nlp.v1.NLPService/RecordFeedback"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	nLPServiceServiceDescriptor                 = v1.File_aleph_nlp_v1_nlp_proto.Services().ByName("NLPService")
	nLPServiceAnalyzeSentimentMethodDescriptor  = nLPServiceServiceDescriptor.Methods().ByName("AnalyzeSentiment")
	nLPServiceStreamPredictionsMethodDescriptor = nLPServiceServiceDescriptor.Methods().ByName("StreamPredictions")
	nLPServiceRecordFeedbackMethodDescriptor    = nLPServiceServiceDescriptor.Methods().ByName("RecordFeedback")
)

// NLPServiceClient is a client for the aleph.nlp.v1.NLPService service.
type NLPServiceClient interface {
	AnalyzeSentiment(context.Context, *connect.Request[v1.AnalyzeSentimentRequest]) (*connect.Response[v1.AnalyzeSentimentResponse], error)
	// Predictive Streams: Receive continuous knowledge updates
	StreamPredictions(context.Context, *connect.Request[v1.StreamPredictionsRequest]) (*connect.ServerStreamForClient[v1.StreamPredictionsResponse], error)
	// Active Learning: Close the loop with user validation
	RecordFeedback(context.Context, *connect.Request[v1.RecordFeedbackRequest]) (*connect.Response[v1.RecordFeedbackResponse], error)
}

// NewNLPServiceClient constructs a client for the aleph.nlp.v1.NLPService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNLPServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NLPServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &nLPServiceClient{
		analyzeSentiment: connect.NewClient[v1.AnalyzeSentimentRequest, v1.AnalyzeSentimentResponse](
			httpClient,
			baseURL+NLPServiceAnalyzeSentimentProcedure,
			connect.WithSchema(nLPServiceAnalyzeSentimentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamPredictions: connect.NewClient[v1.StreamPredictionsRequest, v1.StreamPredictionsResponse](
			httpClient,
			baseURL+NLPServiceStreamPredictionsProcedure,
			connect.WithSchema(nLPServiceStreamPredictionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		recordFeedback: connect.NewClient[v1.RecordFeedbackRequest, v1.RecordFeedbackResponse](
			httpClient,
			baseURL+NLPServiceRecordFeedbackProcedure,
			connect.WithSchema(nLPServiceRecordFeedbackMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// nLPServiceClient implements NLPServiceClient.
type nLPServiceClient struct {
	analyzeSentiment  *connect.Client[v1.AnalyzeSentimentRequest, v1.AnalyzeSentimentResponse]
	streamPredictions *connect.Client[v1.StreamPredictionsRequest, v1.StreamPredictionsResponse]
	recordFeedback    *connect.Client[v1.RecordFeedbackRequest, v1.RecordFeedbackResponse]
}

// AnalyzeSentiment calls aleph.nlp.v1.NLPService.AnalyzeSentiment.
func (c *nLPServiceClient) AnalyzeSentiment(ctx context.Context, req *connect.Request[v1.AnalyzeSentimentRequest]) (*connect.Response[v1.AnalyzeSentimentResponse], error) {
	return c.analyzeSentiment.CallUnary(ctx, req)
}

// StreamPredictions calls aleph.nlp.v1.NLPService.StreamPredictions.
func (c *nLPServiceClient) StreamPredictions(ctx context.Context, req *connect.Request[v1.StreamPredictionsRequest]) (*connect.ServerStreamForClient[v1.StreamPredictionsResponse], error) {
	return c.streamPredictions.CallServerStream(ctx, req)
}

// RecordFeedback calls aleph.nlp.v1.NLPService.RecordFeedback.
func (c *nLPServiceClient) RecordFeedback(ctx context.Context, req *connect.Request[v1.RecordFeedbackRequest]) (*connect.Response[v1.RecordFeedbackResponse], error) {
	return c.recordFeedback.CallUnary(ctx, req)
}

// NLPServiceHandler is an implementation of the aleph.nlp.v1.NLPService service.
type NLPServiceHandler interface {
	AnalyzeSentiment(context.Context, *connect.Request[v1.AnalyzeSentimentRequest]) (*connect.Response[v1.AnalyzeSentimentResponse], error)
	// Predictive Streams: Receive continuous knowledge updates
	StreamPredictions(context.Context, *connect.Request[v1.StreamPredictionsRequest], *connect.ServerStream[v1.StreamPredictionsResponse]) error
	// Active Learning: Close the loop with user validation
	RecordFeedback(context.Context, *connect.Request[v1.RecordFeedbackRequest]) (*connect.Response[v1.RecordFeedbackResponse], error)
}

// NewNLPServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNLPServiceHandler(svc NLPServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nLPServiceAnalyzeSentimentHandler := connect.NewUnaryHandler(
		NLPServiceAnalyzeSentimentProcedure,
		svc.AnalyzeSentiment,
		connect.WithSchema(nLPServiceAnalyzeSentimentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	nLPServiceStreamPredictionsHandler := connect.NewServerStreamHandler(
		NLPServiceStreamPredictionsProcedure,
		svc.StreamPredictions,
		connect.WithSchema(nLPServiceStreamPredictionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	nLPServiceRecordFeedbackHandler := connect.NewUnaryHandler(
		NLPServiceRecordFeedbackProcedure,
		svc.RecordFeedback,
		connect.WithSchema(nLPServiceRecordFeedbackMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.nlp.v1.NLPService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NLPServiceAnalyzeSentimentProcedure:
			nLPServiceAnalyzeSentimentHandler.ServeHTTP(w, r)
		case NLPServiceStreamPredictionsProcedure:
			nLPServiceStreamPredictionsHandler.ServeHTTP(w, r)
		case NLPServiceRecordFeedbackProcedure:
			nLPServiceRecordFeedbackHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNLPServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNLPServiceHandler struct{}

func (UnimplementedNLPServiceHandler) AnalyzeSentiment(context.Context, *connect.Request[v1.AnalyzeSentimentRequest]) (*connect.Response[v1.AnalyzeSentimentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.nlp.v1.NLPService.AnalyzeSentiment is not implemented"))
}

func (UnimplementedNLPServiceHandler) StreamPredictions(context.Context, *connect.Request[v1.StreamPredictionsRequest], *connect.ServerStream[v1.StreamPredictionsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("aleph.nlp.v1.NLPService.StreamPredictions is not implemented"))
}

func (UnimplementedNLPServiceHandler) RecordFeedback(context.Context, *connect.Request[v1.RecordFeedbackRequest]) (*connect.Response[v1.RecordFeedbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.nlp.v1.NLPService.RecordFeedback is not implemented"))
}
