# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nlp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlp.proto\x12\x0c\x61leph.nlp.v1\"i\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x12\n\nis_correct\x18\x02 \x01(\x08\x12\x18\n\x10\x63orrection_value\x18\x03 \x01(\t\x12\x15\n\rfeedback_type\x18\x04 \x01(\t\"#\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x17\x41nalyzeSentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\x18\x41nalyzeSentimentResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x12\r\n\x05label\x18\x02 \x01(\t\"?\n\x11PredictiveRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x16\n\x0eontology_query\x18\x02 \x01(\t\"j\n\x12PredictiveResponse\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x12\x17\n\x0fpredicted_state\x18\x03 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t2\x9a\x02\n\nNLPService\x12\x61\n\x10\x41nalyzeSentiment\x12%.aleph.nlp.v1.AnalyzeSentimentRequest\x1a&.aleph.nlp.v1.AnalyzeSentimentResponse\x12X\n\x11StreamPredictions\x12\x1f.aleph.nlp.v1.PredictiveRequest\x1a .aleph.nlp.v1.PredictiveResponse0\x01\x12O\n\x0eRecordFeedback\x12\x1d.aleph.nlp.v1.FeedbackRequest\x1a\x1e.aleph.nlp.v1.FeedbackResponseB3Z1github.com/ff3300/aleph-v2/internal/api/proto/nlpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/ff3300/aleph-v2/internal/api/proto/nlp'
  _globals['_FEEDBACKREQUEST']._serialized_start=27
  _globals['_FEEDBACKREQUEST']._serialized_end=132
  _globals['_FEEDBACKRESPONSE']._serialized_start=134
  _globals['_FEEDBACKRESPONSE']._serialized_end=169
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_start=171
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_end=210
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_start=212
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_end=268
  _globals['_PREDICTIVEREQUEST']._serialized_start=270
  _globals['_PREDICTIVEREQUEST']._serialized_end=333
  _globals['_PREDICTIVERESPONSE']._serialized_start=335
  _globals['_PREDICTIVERESPONSE']._serialized_end=441
  _globals['_NLPSERVICE']._serialized_start=444
  _globals['_NLPSERVICE']._serialized_end=726
# @@protoc_insertion_point(module_scope)
