# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aleph.nlp.v1 import nlp_pb2 as aleph_dot_nlp_dot_v1_dot_nlp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aleph/nlp/v1/nlp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NLPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/aleph.nlp.v1.NLPService/AnalyzeSentiment',
                request_serializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.AnalyzeSentimentRequest.SerializeToString,
                response_deserializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.AnalyzeSentimentResponse.FromString,
                _registered_method=True)
        self.StreamPredictions = channel.unary_stream(
                '/aleph.nlp.v1.NLPService/StreamPredictions',
                request_serializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.StreamPredictionsRequest.SerializeToString,
                response_deserializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.StreamPredictionsResponse.FromString,
                _registered_method=True)
        self.RecordFeedback = channel.unary_unary(
                '/aleph.nlp.v1.NLPService/RecordFeedback',
                request_serializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.RecordFeedbackRequest.SerializeToString,
                response_deserializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.RecordFeedbackResponse.FromString,
                _registered_method=True)


class NLPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredictions(self, request, context):
        """Predictive Streams: Receive continuous knowledge updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordFeedback(self, request, context):
        """Active Learning: Close the loop with user validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.AnalyzeSentimentRequest.FromString,
                    response_serializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.AnalyzeSentimentResponse.SerializeToString,
            ),
            'StreamPredictions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPredictions,
                    request_deserializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.StreamPredictionsRequest.FromString,
                    response_serializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.StreamPredictionsResponse.SerializeToString,
            ),
            'RecordFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordFeedback,
                    request_deserializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.RecordFeedbackRequest.FromString,
                    response_serializer=aleph_dot_nlp_dot_v1_dot_nlp__pb2.RecordFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aleph.nlp.v1.NLPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aleph.nlp.v1.NLPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NLPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.nlp.v1.NLPService/AnalyzeSentiment',
            aleph_dot_nlp_dot_v1_dot_nlp__pb2.AnalyzeSentimentRequest.SerializeToString,
            aleph_dot_nlp_dot_v1_dot_nlp__pb2.AnalyzeSentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aleph.nlp.v1.NLPService/StreamPredictions',
            aleph_dot_nlp_dot_v1_dot_nlp__pb2.StreamPredictionsRequest.SerializeToString,
            aleph_dot_nlp_dot_v1_dot_nlp__pb2.StreamPredictionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.nlp.v1.NLPService/RecordFeedback',
            aleph_dot_nlp_dot_v1_dot_nlp__pb2.RecordFeedbackRequest.SerializeToString,
            aleph_dot_nlp_dot_v1_dot_nlp__pb2.RecordFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
