// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file aleph/v1/notification.proto (package aleph.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message aleph.v1.SendWebhookRequest
 */
export class SendWebhookRequest extends Message<SendWebhookRequest> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: string payload_json = 2;
   */
  payloadJson = "";

  /**
   * @generated from field: string secret = 3;
   */
  secret = "";

  constructor(data?: PartialMessage<SendWebhookRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.v1.SendWebhookRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "payload_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "secret", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendWebhookRequest {
    return new SendWebhookRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendWebhookRequest {
    return new SendWebhookRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendWebhookRequest {
    return new SendWebhookRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendWebhookRequest | PlainMessage<SendWebhookRequest> | undefined, b: SendWebhookRequest | PlainMessage<SendWebhookRequest> | undefined): boolean {
    return proto3.util.equals(SendWebhookRequest, a, b);
  }
}

/**
 * @generated from message aleph.v1.SendWebhookResponse
 */
export class SendWebhookResponse extends Message<SendWebhookResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<SendWebhookResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.v1.SendWebhookResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendWebhookResponse {
    return new SendWebhookResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendWebhookResponse {
    return new SendWebhookResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendWebhookResponse {
    return new SendWebhookResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendWebhookResponse | PlainMessage<SendWebhookResponse> | undefined, b: SendWebhookResponse | PlainMessage<SendWebhookResponse> | undefined): boolean {
    return proto3.util.equals(SendWebhookResponse, a, b);
  }
}

/**
 * @generated from message aleph.v1.ListChannelsRequest
 */
export class ListChannelsRequest extends Message<ListChannelsRequest> {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId = "";

  constructor(data?: PartialMessage<ListChannelsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.v1.ListChannelsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListChannelsRequest {
    return new ListChannelsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListChannelsRequest {
    return new ListChannelsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListChannelsRequest {
    return new ListChannelsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListChannelsRequest | PlainMessage<ListChannelsRequest> | undefined, b: ListChannelsRequest | PlainMessage<ListChannelsRequest> | undefined): boolean {
    return proto3.util.equals(ListChannelsRequest, a, b);
  }
}

/**
 * @generated from message aleph.v1.ListChannelsResponse
 */
export class ListChannelsResponse extends Message<ListChannelsResponse> {
  /**
   * @generated from field: repeated aleph.v1.NotificationChannel channels = 1;
   */
  channels: NotificationChannel[] = [];

  constructor(data?: PartialMessage<ListChannelsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.v1.ListChannelsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channels", kind: "message", T: NotificationChannel, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListChannelsResponse {
    return new ListChannelsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListChannelsResponse {
    return new ListChannelsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListChannelsResponse {
    return new ListChannelsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListChannelsResponse | PlainMessage<ListChannelsResponse> | undefined, b: ListChannelsResponse | PlainMessage<ListChannelsResponse> | undefined): boolean {
    return proto3.util.equals(ListChannelsResponse, a, b);
  }
}

/**
 * @generated from message aleph.v1.NotificationChannel
 */
export class NotificationChannel extends Message<NotificationChannel> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * "webhook", "email", "slack"
   *
   * @generated from field: string type = 3;
   */
  type = "";

  /**
   * @generated from field: string config_json = 4;
   */
  configJson = "";

  constructor(data?: PartialMessage<NotificationChannel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.v1.NotificationChannel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "config_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NotificationChannel {
    return new NotificationChannel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NotificationChannel {
    return new NotificationChannel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NotificationChannel {
    return new NotificationChannel().fromJsonString(jsonString, options);
  }

  static equals(a: NotificationChannel | PlainMessage<NotificationChannel> | undefined, b: NotificationChannel | PlainMessage<NotificationChannel> | undefined): boolean {
    return proto3.util.equals(NotificationChannel, a, b);
  }
}

