// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file aleph/v1/notification.proto (package aleph.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListChannelsRequest, ListChannelsResponse, SendWebhookRequest, SendWebhookResponse } from "./notification_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service aleph.v1.NotificationService
 */
export const NotificationService = {
  typeName: "aleph.v1.NotificationService",
  methods: {
    /**
     * @generated from rpc aleph.v1.NotificationService.SendWebhook
     */
    sendWebhook: {
      name: "SendWebhook",
      I: SendWebhookRequest,
      O: SendWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.NotificationService.ListChannels
     */
    listChannels: {
      name: "ListChannels",
      I: ListChannelsRequest,
      O: ListChannelsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

