// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file aleph/v1/query.proto (package aleph.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatRequest, ChatResponse, ConfirmActionRequest, ConfirmActionResponse, CreateAgentRequest, CreateAgentResponse, CreateApiKeyRequest, CreateApiKeyResponse, CreateProjectRequest, CreateProjectResponse, CreateSkillRequest, CreateSkillResponse, CreateTaskRequest, CreateTaskResponse, CreateToolRequest, CreateToolResponse, DeleteAgentRequest, DeleteAgentResponse, DeleteApiKeyRequest, DeleteApiKeyResponse, DeleteAssetRequest, DeleteAssetResponse, DeleteProjectRequest, DeleteProjectResponse, DeleteSkillRequest, DeleteSkillResponse, DeleteTaskRequest, DeleteTaskResponse, DeleteToolRequest, DeleteToolResponse, EmergeOntologyRequest, EmergeOntologyResponse, ExecuteQueryRequest, ExecuteQueryResponse, GeneratePdfRequest, GeneratePdfResponse, GetAssetContentRequest, GetAssetContentResponse, GetChatHistoryRequest, GetChatHistoryResponse, GetChecksumRequest, GetChecksumResponse, GetDataLineageRequest, GetDataLineageResponse, GetDataStatsRequest, GetDataStatsResponse, GetOntologyRequest, GetOntologyResponse, GetProgressRequest, GetProgressResponse, GetTaskLogsRequest, GetTaskLogsResponse, GlobalQueryRequest, GlobalQueryResponse, ListAgentsRequest, ListAgentsResponse, ListApiKeysRequest, ListApiKeysResponse, ListAssetsRequest, ListAssetsResponse, ListModelsRequest, ListModelsResponse, ListProjectsRequest, ListProjectsResponse, ListSkillsRequest, ListSkillsResponse, ListTasksRequest, ListTasksResponse, ListToolsRequest, ListToolsResponse, RunTaskRequest, RunTaskResponse, SaveOntologyRequest, SaveOntologyResponse, UpdateAgentRequest, UpdateAgentResponse, UpdateSkillRequest, UpdateSkillResponse, UpdateToolRequest, UpdateToolResponse, UploadAssetRequest, UploadAssetResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service aleph.v1.QueryService
 */
export const QueryService = {
  typeName: "aleph.v1.QueryService",
  methods: {
    /**
     * @generated from rpc aleph.v1.QueryService.ExecuteQuery
     */
    executeQuery: {
      name: "ExecuteQuery",
      I: ExecuteQueryRequest,
      O: ExecuteQueryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.Chat
     */
    chat: {
      name: "Chat",
      I: ChatRequest,
      O: ChatResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.GetChatHistory
     */
    getChatHistory: {
      name: "GetChatHistory",
      I: GetChatHistoryRequest,
      O: GetChatHistoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.GetDataStats
     */
    getDataStats: {
      name: "GetDataStats",
      I: GetDataStatsRequest,
      O: GetDataStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.ConfirmAction
     */
    confirmAction: {
      name: "ConfirmAction",
      I: ConfirmActionRequest,
      O: ConfirmActionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.GlobalQuery
     */
    globalQuery: {
      name: "GlobalQuery",
      I: GlobalQueryRequest,
      O: GlobalQueryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.GetDataLineage
     */
    getDataLineage: {
      name: "GetDataLineage",
      I: GetDataLineageRequest,
      O: GetDataLineageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.QueryService.GetChecksum
     */
    getChecksum: {
      name: "GetChecksum",
      I: GetChecksumRequest,
      O: GetChecksumResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.ProjectService
 */
export const ProjectService = {
  typeName: "aleph.v1.ProjectService",
  methods: {
    /**
     * @generated from rpc aleph.v1.ProjectService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ProjectService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ProjectService.DeleteProject
     */
    deleteProject: {
      name: "DeleteProject",
      I: DeleteProjectRequest,
      O: DeleteProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ProjectService.EmergeOntology
     */
    emergeOntology: {
      name: "EmergeOntology",
      I: EmergeOntologyRequest,
      O: EmergeOntologyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ProjectService.GetOntology
     */
    getOntology: {
      name: "GetOntology",
      I: GetOntologyRequest,
      O: GetOntologyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ProjectService.SaveOntology
     */
    saveOntology: {
      name: "SaveOntology",
      I: SaveOntologyRequest,
      O: SaveOntologyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.IngestionService
 */
export const IngestionService = {
  typeName: "aleph.v1.IngestionService",
  methods: {
    /**
     * @generated from rpc aleph.v1.IngestionService.ListTasks
     */
    listTasks: {
      name: "ListTasks",
      I: ListTasksRequest,
      O: ListTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.IngestionService.CreateTask
     */
    createTask: {
      name: "CreateTask",
      I: CreateTaskRequest,
      O: CreateTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.IngestionService.DeleteTask
     */
    deleteTask: {
      name: "DeleteTask",
      I: DeleteTaskRequest,
      O: DeleteTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.IngestionService.RunTask
     */
    runTask: {
      name: "RunTask",
      I: RunTaskRequest,
      O: RunTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.IngestionService.GetTaskLogs
     */
    getTaskLogs: {
      name: "GetTaskLogs",
      I: GetTaskLogsRequest,
      O: GetTaskLogsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.IngestionService.GetProgress
     */
    getProgress: {
      name: "GetProgress",
      I: GetProgressRequest,
      O: GetProgressResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.AgentService
 */
export const AgentService = {
  typeName: "aleph.v1.AgentService",
  methods: {
    /**
     * @generated from rpc aleph.v1.AgentService.ListAgents
     */
    listAgents: {
      name: "ListAgents",
      I: ListAgentsRequest,
      O: ListAgentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.AgentService.CreateAgent
     */
    createAgent: {
      name: "CreateAgent",
      I: CreateAgentRequest,
      O: CreateAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.AgentService.DeleteAgent
     */
    deleteAgent: {
      name: "DeleteAgent",
      I: DeleteAgentRequest,
      O: DeleteAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.AgentService.UpdateAgent
     */
    updateAgent: {
      name: "UpdateAgent",
      I: UpdateAgentRequest,
      O: UpdateAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.AgentService.ListModels
     */
    listModels: {
      name: "ListModels",
      I: ListModelsRequest,
      O: ListModelsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.SkillService
 */
export const SkillService = {
  typeName: "aleph.v1.SkillService",
  methods: {
    /**
     * @generated from rpc aleph.v1.SkillService.ListSkills
     */
    listSkills: {
      name: "ListSkills",
      I: ListSkillsRequest,
      O: ListSkillsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.SkillService.CreateSkill
     */
    createSkill: {
      name: "CreateSkill",
      I: CreateSkillRequest,
      O: CreateSkillResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.SkillService.UpdateSkill
     */
    updateSkill: {
      name: "UpdateSkill",
      I: UpdateSkillRequest,
      O: UpdateSkillResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.SkillService.DeleteSkill
     */
    deleteSkill: {
      name: "DeleteSkill",
      I: DeleteSkillRequest,
      O: DeleteSkillResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.ToolService
 */
export const ToolService = {
  typeName: "aleph.v1.ToolService",
  methods: {
    /**
     * @generated from rpc aleph.v1.ToolService.ListTools
     */
    listTools: {
      name: "ListTools",
      I: ListToolsRequest,
      O: ListToolsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ToolService.CreateTool
     */
    createTool: {
      name: "CreateTool",
      I: CreateToolRequest,
      O: CreateToolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ToolService.UpdateTool
     */
    updateTool: {
      name: "UpdateTool",
      I: UpdateToolRequest,
      O: UpdateToolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.ToolService.DeleteTool
     */
    deleteTool: {
      name: "DeleteTool",
      I: DeleteToolRequest,
      O: DeleteToolResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.LibraryService
 */
export const LibraryService = {
  typeName: "aleph.v1.LibraryService",
  methods: {
    /**
     * @generated from rpc aleph.v1.LibraryService.ListAssets
     */
    listAssets: {
      name: "ListAssets",
      I: ListAssetsRequest,
      O: ListAssetsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.LibraryService.GetAssetContent
     */
    getAssetContent: {
      name: "GetAssetContent",
      I: GetAssetContentRequest,
      O: GetAssetContentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.LibraryService.DeleteAsset
     */
    deleteAsset: {
      name: "DeleteAsset",
      I: DeleteAssetRequest,
      O: DeleteAssetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.LibraryService.GeneratePdf
     */
    generatePdf: {
      name: "GeneratePdf",
      I: GeneratePdfRequest,
      O: GeneratePdfResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.LibraryService.UploadAsset
     */
    uploadAsset: {
      name: "UploadAsset",
      I: UploadAssetRequest,
      O: UploadAssetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service aleph.v1.AuthService
 */
export const AuthService = {
  typeName: "aleph.v1.AuthService",
  methods: {
    /**
     * @generated from rpc aleph.v1.AuthService.ListApiKeys
     */
    listApiKeys: {
      name: "ListApiKeys",
      I: ListApiKeysRequest,
      O: ListApiKeysResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.AuthService.CreateApiKey
     */
    createApiKey: {
      name: "CreateApiKey",
      I: CreateApiKeyRequest,
      O: CreateApiKeyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.v1.AuthService.DeleteApiKey
     */
    deleteApiKey: {
      name: "DeleteApiKey",
      I: DeleteApiKeyRequest,
      O: DeleteApiKeyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

