// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file aleph/v1/registry.proto (package aleph.registry.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetComponentRequest, GetComponentResponse, ListComponentsRequest, ListComponentsResponse, RegisterComponentRequest, RegisterComponentResponse, UpdateComponentStatusRequest, UpdateComponentStatusResponse } from "./registry_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service aleph.registry.v1.RegistryService
 */
export const RegistryService = {
  typeName: "aleph.registry.v1.RegistryService",
  methods: {
    /**
     * @generated from rpc aleph.registry.v1.RegistryService.RegisterComponent
     */
    registerComponent: {
      name: "RegisterComponent",
      I: RegisterComponentRequest,
      O: RegisterComponentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.registry.v1.RegistryService.GetComponent
     */
    getComponent: {
      name: "GetComponent",
      I: GetComponentRequest,
      O: GetComponentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.registry.v1.RegistryService.ListComponents
     */
    listComponents: {
      name: "ListComponents",
      I: ListComponentsRequest,
      O: ListComponentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.registry.v1.RegistryService.UpdateComponentStatus
     */
    updateComponentStatus: {
      name: "UpdateComponentStatus",
      I: UpdateComponentStatusRequest,
      O: UpdateComponentStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

