// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file aleph/v1/registry.proto (package aleph.registry.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message aleph.registry.v1.ComponentMetadata
 */
export class ComponentMetadata extends Message<ComponentMetadata> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: string version = 4;
   */
  version = "";

  /**
   * @generated from field: string type = 5;
   */
  type = "";

  /**
   * @generated from field: string category = 6;
   */
  category = "";

  /**
   * @generated from field: string source = 7;
   */
  source = "";

  /**
   * @generated from field: optional string config_schema_json = 8;
   */
  configSchemaJson?: string;

  /**
   * @generated from field: optional string execution_command = 9;
   */
  executionCommand?: string;

  /**
   * @generated from field: optional string dependencies_json = 10;
   */
  dependenciesJson?: string;

  /**
   * @generated from field: optional string input_schema_json = 11;
   */
  inputSchemaJson?: string;

  /**
   * @generated from field: optional string output_schema_json = 12;
   */
  outputSchemaJson?: string;

  /**
   * @generated from field: optional string prompt_template = 13;
   */
  promptTemplate?: string;

  /**
   * @generated from field: optional string tool_ids_json = 14;
   */
  toolIdsJson?: string;

  /**
   * @generated from field: optional double avg_latency_ms = 15;
   */
  avgLatencyMs?: number;

  /**
   * @generated from field: optional double avg_brier_score = 16;
   */
  avgBrierScore?: number;

  /**
   * @generated from field: optional double avg_cpu_usage = 17;
   */
  avgCpuUsage?: number;

  /**
   * @generated from field: optional double avg_memory_mb = 18;
   */
  avgMemoryMb?: number;

  /**
   * @generated from field: optional double avg_exec_time_ms = 19;
   */
  avgExecTimeMs?: number;

  /**
   * @generated from field: string status = 20;
   */
  status = "";

  /**
   * @generated from field: string approval_status = 21;
   */
  approvalStatus = "";

  /**
   * @generated from field: optional float trust_score = 22;
   */
  trustScore?: number;

  /**
   * @generated from field: optional string created_by_agent_id = 23;
   */
  createdByAgentId?: string;

  /**
   * @generated from field: google.protobuf.Timestamp creation_timestamp = 24;
   */
  creationTimestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_updated_timestamp = 25;
   */
  lastUpdatedTimestamp?: Timestamp;

  constructor(data?: PartialMessage<ComponentMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.ComponentMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "config_schema_json", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "execution_command", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "dependencies_json", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "input_schema_json", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 12, name: "output_schema_json", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 13, name: "prompt_template", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 14, name: "tool_ids_json", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 15, name: "avg_latency_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 16, name: "avg_brier_score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 17, name: "avg_cpu_usage", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 18, name: "avg_memory_mb", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 19, name: "avg_exec_time_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 20, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "approval_status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "trust_score", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 23, name: "created_by_agent_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 24, name: "creation_timestamp", kind: "message", T: Timestamp },
    { no: 25, name: "last_updated_timestamp", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ComponentMetadata {
    return new ComponentMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ComponentMetadata {
    return new ComponentMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ComponentMetadata {
    return new ComponentMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: ComponentMetadata | PlainMessage<ComponentMetadata> | undefined, b: ComponentMetadata | PlainMessage<ComponentMetadata> | undefined): boolean {
    return proto3.util.equals(ComponentMetadata, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.RegisterComponentRequest
 */
export class RegisterComponentRequest extends Message<RegisterComponentRequest> {
  /**
   * @generated from field: aleph.registry.v1.ComponentMetadata metadata = 1;
   */
  metadata?: ComponentMetadata;

  constructor(data?: PartialMessage<RegisterComponentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.RegisterComponentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metadata", kind: "message", T: ComponentMetadata },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterComponentRequest {
    return new RegisterComponentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterComponentRequest {
    return new RegisterComponentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterComponentRequest {
    return new RegisterComponentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterComponentRequest | PlainMessage<RegisterComponentRequest> | undefined, b: RegisterComponentRequest | PlainMessage<RegisterComponentRequest> | undefined): boolean {
    return proto3.util.equals(RegisterComponentRequest, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.RegisterComponentResponse
 */
export class RegisterComponentResponse extends Message<RegisterComponentResponse> {
  /**
   * @generated from field: string component_id = 1;
   */
  componentId = "";

  constructor(data?: PartialMessage<RegisterComponentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.RegisterComponentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "component_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterComponentResponse {
    return new RegisterComponentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterComponentResponse {
    return new RegisterComponentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterComponentResponse {
    return new RegisterComponentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterComponentResponse | PlainMessage<RegisterComponentResponse> | undefined, b: RegisterComponentResponse | PlainMessage<RegisterComponentResponse> | undefined): boolean {
    return proto3.util.equals(RegisterComponentResponse, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.GetComponentRequest
 */
export class GetComponentRequest extends Message<GetComponentRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetComponentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.GetComponentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetComponentRequest {
    return new GetComponentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetComponentRequest {
    return new GetComponentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetComponentRequest {
    return new GetComponentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetComponentRequest | PlainMessage<GetComponentRequest> | undefined, b: GetComponentRequest | PlainMessage<GetComponentRequest> | undefined): boolean {
    return proto3.util.equals(GetComponentRequest, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.GetComponentResponse
 */
export class GetComponentResponse extends Message<GetComponentResponse> {
  /**
   * @generated from field: aleph.registry.v1.ComponentMetadata metadata = 1;
   */
  metadata?: ComponentMetadata;

  constructor(data?: PartialMessage<GetComponentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.GetComponentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metadata", kind: "message", T: ComponentMetadata },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetComponentResponse {
    return new GetComponentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetComponentResponse {
    return new GetComponentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetComponentResponse {
    return new GetComponentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetComponentResponse | PlainMessage<GetComponentResponse> | undefined, b: GetComponentResponse | PlainMessage<GetComponentResponse> | undefined): boolean {
    return proto3.util.equals(GetComponentResponse, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.ListComponentsRequest
 */
export class ListComponentsRequest extends Message<ListComponentsRequest> {
  /**
   * @generated from field: map<string, string> filter = 1;
   */
  filter: { [key: string]: string } = {};

  constructor(data?: PartialMessage<ListComponentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.ListComponentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filter", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListComponentsRequest {
    return new ListComponentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListComponentsRequest {
    return new ListComponentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListComponentsRequest {
    return new ListComponentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListComponentsRequest | PlainMessage<ListComponentsRequest> | undefined, b: ListComponentsRequest | PlainMessage<ListComponentsRequest> | undefined): boolean {
    return proto3.util.equals(ListComponentsRequest, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.ListComponentsResponse
 */
export class ListComponentsResponse extends Message<ListComponentsResponse> {
  /**
   * @generated from field: repeated aleph.registry.v1.ComponentMetadata components = 1;
   */
  components: ComponentMetadata[] = [];

  constructor(data?: PartialMessage<ListComponentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.ListComponentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "components", kind: "message", T: ComponentMetadata, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListComponentsResponse {
    return new ListComponentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListComponentsResponse {
    return new ListComponentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListComponentsResponse {
    return new ListComponentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListComponentsResponse | PlainMessage<ListComponentsResponse> | undefined, b: ListComponentsResponse | PlainMessage<ListComponentsResponse> | undefined): boolean {
    return proto3.util.equals(ListComponentsResponse, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.UpdateComponentStatusRequest
 */
export class UpdateComponentStatusRequest extends Message<UpdateComponentStatusRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string status = 2;
   */
  status = "";

  constructor(data?: PartialMessage<UpdateComponentStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.UpdateComponentStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateComponentStatusRequest {
    return new UpdateComponentStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateComponentStatusRequest {
    return new UpdateComponentStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateComponentStatusRequest {
    return new UpdateComponentStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateComponentStatusRequest | PlainMessage<UpdateComponentStatusRequest> | undefined, b: UpdateComponentStatusRequest | PlainMessage<UpdateComponentStatusRequest> | undefined): boolean {
    return proto3.util.equals(UpdateComponentStatusRequest, a, b);
  }
}

/**
 * @generated from message aleph.registry.v1.UpdateComponentStatusResponse
 */
export class UpdateComponentStatusResponse extends Message<UpdateComponentStatusResponse> {
  constructor(data?: PartialMessage<UpdateComponentStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.registry.v1.UpdateComponentStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateComponentStatusResponse {
    return new UpdateComponentStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateComponentStatusResponse {
    return new UpdateComponentStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateComponentStatusResponse {
    return new UpdateComponentStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateComponentStatusResponse | PlainMessage<UpdateComponentStatusResponse> | undefined, b: UpdateComponentStatusResponse | PlainMessage<UpdateComponentStatusResponse> | undefined): boolean {
    return proto3.util.equals(UpdateComponentStatusResponse, a, b);
  }
}

