// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file aleph/v1/sandbox.proto (package aleph.tool.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Struct } from "@bufbuild/protobuf";

/**
 * @generated from message aleph.tool.v1.ExecutionResult
 */
export class ExecutionResult extends Message<ExecutionResult> {
  /**
   * @generated from field: string stdout = 1;
   */
  stdout = "";

  /**
   * @generated from field: string stderr = 2;
   */
  stderr = "";

  /**
   * @generated from field: int32 exit_code = 3;
   */
  exitCode = 0;

  /**
   * @generated from field: string error = 4;
   */
  error = "";

  /**
   * @generated from field: string metrics_json = 5;
   */
  metricsJson = "";

  constructor(data?: PartialMessage<ExecutionResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.tool.v1.ExecutionResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stdout", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "stderr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "exit_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "metrics_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExecutionResult {
    return new ExecutionResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExecutionResult {
    return new ExecutionResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExecutionResult {
    return new ExecutionResult().fromJsonString(jsonString, options);
  }

  static equals(a: ExecutionResult | PlainMessage<ExecutionResult> | undefined, b: ExecutionResult | PlainMessage<ExecutionResult> | undefined): boolean {
    return proto3.util.equals(ExecutionResult, a, b);
  }
}

/**
 * @generated from message aleph.tool.v1.ExecuteToolRequest
 */
export class ExecuteToolRequest extends Message<ExecuteToolRequest> {
  /**
   * @generated from field: string tool_id = 1;
   */
  toolId = "";

  /**
   * @generated from field: google.protobuf.Struct input_params = 2;
   */
  inputParams?: Struct;

  constructor(data?: PartialMessage<ExecuteToolRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.tool.v1.ExecuteToolRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tool_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "input_params", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExecuteToolRequest {
    return new ExecuteToolRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExecuteToolRequest {
    return new ExecuteToolRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExecuteToolRequest {
    return new ExecuteToolRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ExecuteToolRequest | PlainMessage<ExecuteToolRequest> | undefined, b: ExecuteToolRequest | PlainMessage<ExecuteToolRequest> | undefined): boolean {
    return proto3.util.equals(ExecuteToolRequest, a, b);
  }
}

/**
 * @generated from message aleph.tool.v1.ExecuteToolResponse
 */
export class ExecuteToolResponse extends Message<ExecuteToolResponse> {
  /**
   * @generated from field: aleph.tool.v1.ExecutionResult result = 1;
   */
  result?: ExecutionResult;

  constructor(data?: PartialMessage<ExecuteToolResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.tool.v1.ExecuteToolResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "message", T: ExecutionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExecuteToolResponse {
    return new ExecuteToolResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExecuteToolResponse {
    return new ExecuteToolResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExecuteToolResponse {
    return new ExecuteToolResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExecuteToolResponse | PlainMessage<ExecuteToolResponse> | undefined, b: ExecuteToolResponse | PlainMessage<ExecuteToolResponse> | undefined): boolean {
    return proto3.util.equals(ExecuteToolResponse, a, b);
  }
}

/**
 * @generated from message aleph.tool.v1.RunSkillRequest
 */
export class RunSkillRequest extends Message<RunSkillRequest> {
  /**
   * @generated from field: string skill_id = 1;
   */
  skillId = "";

  /**
   * @generated from field: google.protobuf.Struct input_params = 2;
   */
  inputParams?: Struct;

  /**
   * @generated from field: map<string, string> context = 3;
   */
  context: { [key: string]: string } = {};

  constructor(data?: PartialMessage<RunSkillRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.tool.v1.RunSkillRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "skill_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "input_params", kind: "message", T: Struct },
    { no: 3, name: "context", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunSkillRequest {
    return new RunSkillRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunSkillRequest {
    return new RunSkillRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunSkillRequest {
    return new RunSkillRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RunSkillRequest | PlainMessage<RunSkillRequest> | undefined, b: RunSkillRequest | PlainMessage<RunSkillRequest> | undefined): boolean {
    return proto3.util.equals(RunSkillRequest, a, b);
  }
}

/**
 * @generated from message aleph.tool.v1.RunSkillResponse
 */
export class RunSkillResponse extends Message<RunSkillResponse> {
  /**
   * @generated from field: aleph.tool.v1.ExecutionResult result = 1;
   */
  result?: ExecutionResult;

  constructor(data?: PartialMessage<RunSkillResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.tool.v1.RunSkillResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "message", T: ExecutionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunSkillResponse {
    return new RunSkillResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunSkillResponse {
    return new RunSkillResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunSkillResponse {
    return new RunSkillResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RunSkillResponse | PlainMessage<RunSkillResponse> | undefined, b: RunSkillResponse | PlainMessage<RunSkillResponse> | undefined): boolean {
    return proto3.util.equals(RunSkillResponse, a, b);
  }
}

