// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file aleph/v1/sandbox.proto (package aleph.tool.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExecuteToolRequest, ExecuteToolResponse, RunSkillRequest, RunSkillResponse } from "./sandbox_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service aleph.tool.v1.SandboxService
 */
export const SandboxService = {
  typeName: "aleph.tool.v1.SandboxService",
  methods: {
    /**
     * @generated from rpc aleph.tool.v1.SandboxService.ExecuteTool
     */
    executeTool: {
      name: "ExecuteTool",
      I: ExecuteToolRequest,
      O: ExecuteToolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc aleph.tool.v1.SandboxService.RunSkill
     */
    runSkill: {
      name: "RunSkill",
      I: RunSkillRequest,
      O: RunSkillResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

