{{- if not .Values.postgres.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aleph-v2.postgres.secretName" . }}
  labels:
    {{- include "aleph-v2.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
  dsn: {{ printf "postgres://%s:%s@%s-postgres:%d/%s?sslmode=disable" .Values.postgres.auth.username .Values.postgres.auth.password (include "aleph-v2.fullname" .) (int .Values.postgres.service.port) .Values.postgres.auth.database | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aleph-v2.fullname" . }}-backend
  labels:
    {{- include "aleph-v2.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  encryption-key: {{ .Values.backend.secrets.encryptionKey | default "" | b64enc | quote }}
