ALTER TABLE system_tools ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE system_tools ADD COLUMN IF NOT EXISTS version TEXT NOT NULL DEFAULT '1.0.0';
ALTER TABLE system_tools ADD COLUMN IF NOT EXISTS health_status TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE system_tools ADD COLUMN IF NOT EXISTS last_checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE system_tools ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'builtin';