// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ontology.proto

package ontologyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/ontology/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OntologyNegotiationServiceName is the fully-qualified name of the OntologyNegotiationService service.
	OntologyNegotiationServiceName = "aleph.ontology.v1.OntologyNegotiationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OntologyNegotiationServiceProposeProcedure is the fully-qualified name of the
	// OntologyNegotiationService's Propose RPC.
	OntologyNegotiationServiceProposeProcedure = "/aleph.ontology.v1.OntologyNegotiationService/Propose"
	// OntologyNegotiationServiceAcceptProcedure is the fully-qualified name of the
	// OntologyNegotiationService's Accept RPC.
	OntologyNegotiationServiceAcceptProcedure = "/aleph.ontology.v1.OntologyNegotiationService/Accept"
	// OntologyNegotiationServiceRejectProcedure is the fully-qualified name of the
	// OntologyNegotiationService's Reject RPC.
	OntologyNegotiationServiceRejectProcedure = "/aleph.ontology.v1.OntologyNegotiationService/Reject"
	// OntologyNegotiationServiceModifyProcedure is the fully-qualified name of the
	// OntologyNegotiationService's Modify RPC.
	OntologyNegotiationServiceModifyProcedure = "/aleph.ontology.v1.OntologyNegotiationService/Modify"
	// OntologyNegotiationServiceListVersionsProcedure is the fully-qualified name of the
	// OntologyNegotiationService's ListVersions RPC.
	OntologyNegotiationServiceListVersionsProcedure = "/aleph.ontology.v1.OntologyNegotiationService/ListVersions"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	ontologyNegotiationServiceServiceDescriptor            = v1.File_aleph_ontology_v1_proto.Services().ByName("OntologyNegotiationService")
	ontologyNegotiationServiceProposeMethodDescriptor      = ontologyNegotiationServiceServiceDescriptor.Methods().ByName("Propose")
	ontologyNegotiationServiceAcceptMethodDescriptor       = ontologyNegotiationServiceServiceDescriptor.Methods().ByName("Accept")
	ontologyNegotiationServiceRejectMethodDescriptor       = ontologyNegotiationServiceServiceDescriptor.Methods().ByName("Reject")
	ontologyNegotiationServiceModifyMethodDescriptor       = ontologyNegotiationServiceServiceDescriptor.Methods().ByName("Modify")
	ontologyNegotiationServiceListVersionsMethodDescriptor = ontologyNegotiationServiceServiceDescriptor.Methods().ByName("ListVersions")
)

// OntologyNegotiationServiceClient is a client for the
// aleph.ontology.v1.OntologyNegotiationService service.
type OntologyNegotiationServiceClient interface {
	Propose(context.Context, *connect.Request[v1.ProposeRequest]) (*connect.Response[v1.ProposeResponse], error)
	Accept(context.Context, *connect.Request[v1.AcceptRequest]) (*connect.Response[v1.AcceptResponse], error)
	Reject(context.Context, *connect.Request[v1.RejectRequest]) (*connect.Response[v1.RejectResponse], error)
	Modify(context.Context, *connect.Request[v1.ModifyRequest]) (*connect.Response[v1.ModifyResponse], error)
	ListVersions(context.Context, *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error)
}

// NewOntologyNegotiationServiceClient constructs a client for the
// aleph.ontology.v1.OntologyNegotiationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOntologyNegotiationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OntologyNegotiationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &ontologyNegotiationServiceClient{
		propose: connect.NewClient[v1.ProposeRequest, v1.ProposeResponse](
			httpClient,
			baseURL+OntologyNegotiationServiceProposeProcedure,
			connect.WithSchema(ontologyNegotiationServiceProposeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		accept: connect.NewClient[v1.AcceptRequest, v1.AcceptResponse](
			httpClient,
			baseURL+OntologyNegotiationServiceAcceptProcedure,
			connect.WithSchema(ontologyNegotiationServiceAcceptMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		reject: connect.NewClient[v1.RejectRequest, v1.RejectResponse](
			httpClient,
			baseURL+OntologyNegotiationServiceRejectProcedure,
			connect.WithSchema(ontologyNegotiationServiceRejectMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		modify: connect.NewClient[v1.ModifyRequest, v1.ModifyResponse](
			httpClient,
			baseURL+OntologyNegotiationServiceModifyProcedure,
			connect.WithSchema(ontologyNegotiationServiceModifyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listVersions: connect.NewClient[v1.ListVersionsRequest, v1.ListVersionsResponse](
			httpClient,
			baseURL+OntologyNegotiationServiceListVersionsProcedure,
			connect.WithSchema(ontologyNegotiationServiceListVersionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// ontologyNegotiationServiceClient implements OntologyNegotiationServiceClient.
type ontologyNegotiationServiceClient struct {
	propose      *connect.Client[v1.ProposeRequest, v1.ProposeResponse]
	accept       *connect.Client[v1.AcceptRequest, v1.AcceptResponse]
	reject       *connect.Client[v1.RejectRequest, v1.RejectResponse]
	modify       *connect.Client[v1.ModifyRequest, v1.ModifyResponse]
	listVersions *connect.Client[v1.ListVersionsRequest, v1.ListVersionsResponse]
}

// Propose calls aleph.ontology.v1.OntologyNegotiationService.Propose.
func (c *ontologyNegotiationServiceClient) Propose(ctx context.Context, req *connect.Request[v1.ProposeRequest]) (*connect.Response[v1.ProposeResponse], error) {
	return c.propose.CallUnary(ctx, req)
}

// Accept calls aleph.ontology.v1.OntologyNegotiationService.Accept.
func (c *ontologyNegotiationServiceClient) Accept(ctx context.Context, req *connect.Request[v1.AcceptRequest]) (*connect.Response[v1.AcceptResponse], error) {
	return c.accept.CallUnary(ctx, req)
}

// Reject calls aleph.ontology.v1.OntologyNegotiationService.Reject.
func (c *ontologyNegotiationServiceClient) Reject(ctx context.Context, req *connect.Request[v1.RejectRequest]) (*connect.Response[v1.RejectResponse], error) {
	return c.reject.CallUnary(ctx, req)
}

// Modify calls aleph.ontology.v1.OntologyNegotiationService.Modify.
func (c *ontologyNegotiationServiceClient) Modify(ctx context.Context, req *connect.Request[v1.ModifyRequest]) (*connect.Response[v1.ModifyResponse], error) {
	return c.modify.CallUnary(ctx, req)
}

// ListVersions calls aleph.ontology.v1.OntologyNegotiationService.ListVersions.
func (c *ontologyNegotiationServiceClient) ListVersions(ctx context.Context, req *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error) {
	return c.listVersions.CallUnary(ctx, req)
}

// OntologyNegotiationServiceHandler is an implementation of the
// aleph.ontology.v1.OntologyNegotiationService service.
type OntologyNegotiationServiceHandler interface {
	Propose(context.Context, *connect.Request[v1.ProposeRequest]) (*connect.Response[v1.ProposeResponse], error)
	Accept(context.Context, *connect.Request[v1.AcceptRequest]) (*connect.Response[v1.AcceptResponse], error)
	Reject(context.Context, *connect.Request[v1.RejectRequest]) (*connect.Response[v1.RejectResponse], error)
	Modify(context.Context, *connect.Request[v1.ModifyRequest]) (*connect.Response[v1.ModifyResponse], error)
	ListVersions(context.Context, *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error)
}

// NewOntologyNegotiationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOntologyNegotiationServiceHandler(svc OntologyNegotiationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ontologyNegotiationServiceProposeHandler := connect.NewUnaryHandler(
		OntologyNegotiationServiceProposeProcedure,
		svc.Propose,
		connect.WithSchema(ontologyNegotiationServiceProposeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ontologyNegotiationServiceAcceptHandler := connect.NewUnaryHandler(
		OntologyNegotiationServiceAcceptProcedure,
		svc.Accept,
		connect.WithSchema(ontologyNegotiationServiceAcceptMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ontologyNegotiationServiceRejectHandler := connect.NewUnaryHandler(
		OntologyNegotiationServiceRejectProcedure,
		svc.Reject,
		connect.WithSchema(ontologyNegotiationServiceRejectMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ontologyNegotiationServiceModifyHandler := connect.NewUnaryHandler(
		OntologyNegotiationServiceModifyProcedure,
		svc.Modify,
		connect.WithSchema(ontologyNegotiationServiceModifyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ontologyNegotiationServiceListVersionsHandler := connect.NewUnaryHandler(
		OntologyNegotiationServiceListVersionsProcedure,
		svc.ListVersions,
		connect.WithSchema(ontologyNegotiationServiceListVersionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.ontology.v1.OntologyNegotiationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OntologyNegotiationServiceProposeProcedure:
			ontologyNegotiationServiceProposeHandler.ServeHTTP(w, r)
		case OntologyNegotiationServiceAcceptProcedure:
			ontologyNegotiationServiceAcceptHandler.ServeHTTP(w, r)
		case OntologyNegotiationServiceRejectProcedure:
			ontologyNegotiationServiceRejectHandler.ServeHTTP(w, r)
		case OntologyNegotiationServiceModifyProcedure:
			ontologyNegotiationServiceModifyHandler.ServeHTTP(w, r)
		case OntologyNegotiationServiceListVersionsProcedure:
			ontologyNegotiationServiceListVersionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOntologyNegotiationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOntologyNegotiationServiceHandler struct{}

func (UnimplementedOntologyNegotiationServiceHandler) Propose(context.Context, *connect.Request[v1.ProposeRequest]) (*connect.Response[v1.ProposeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.ontology.v1.OntologyNegotiationService.Propose is not implemented"))
}

func (UnimplementedOntologyNegotiationServiceHandler) Accept(context.Context, *connect.Request[v1.AcceptRequest]) (*connect.Response[v1.AcceptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.ontology.v1.OntologyNegotiationService.Accept is not implemented"))
}

func (UnimplementedOntologyNegotiationServiceHandler) Reject(context.Context, *connect.Request[v1.RejectRequest]) (*connect.Response[v1.RejectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.ontology.v1.OntologyNegotiationService.Reject is not implemented"))
}

func (UnimplementedOntologyNegotiationServiceHandler) Modify(context.Context, *connect.Request[v1.ModifyRequest]) (*connect.Response[v1.ModifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.ontology.v1.OntologyNegotiationService.Modify is not implemented"))
}

func (UnimplementedOntologyNegotiationServiceHandler) ListVersions(context.Context, *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.ontology.v1.OntologyNegotiationService.ListVersions is not implemented"))
}
