// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aleph/v1/manifest.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DiscoveryServiceName is the fully-qualified name of the DiscoveryService service.
	DiscoveryServiceName = "aleph.v1.DiscoveryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DiscoveryServiceDiscoverDatabaseProcedure is the fully-qualified name of the DiscoveryService's
	// DiscoverDatabase RPC.
	DiscoveryServiceDiscoverDatabaseProcedure = "/aleph.v1.DiscoveryService/DiscoverDatabase"
	// DiscoveryServiceGetManifestProcedure is the fully-qualified name of the DiscoveryService's
	// GetManifest RPC.
	DiscoveryServiceGetManifestProcedure = "/aleph.v1.DiscoveryService/GetManifest"
	// DiscoveryServiceSaveManifestProcedure is the fully-qualified name of the DiscoveryService's
	// SaveManifest RPC.
	DiscoveryServiceSaveManifestProcedure = "/aleph.v1.DiscoveryService/SaveManifest"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	discoveryServiceServiceDescriptor                = v1.File_aleph_v1_manifest_proto.Services().ByName("DiscoveryService")
	discoveryServiceDiscoverDatabaseMethodDescriptor = discoveryServiceServiceDescriptor.Methods().ByName("DiscoverDatabase")
	discoveryServiceGetManifestMethodDescriptor      = discoveryServiceServiceDescriptor.Methods().ByName("GetManifest")
	discoveryServiceSaveManifestMethodDescriptor     = discoveryServiceServiceDescriptor.Methods().ByName("SaveManifest")
)

// DiscoveryServiceClient is a client for the aleph.v1.DiscoveryService service.
type DiscoveryServiceClient interface {
	DiscoverDatabase(context.Context, *connect.Request[v1.DiscoverDatabaseRequest]) (*connect.Response[v1.DiscoverDatabaseResponse], error)
	GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error)
	SaveManifest(context.Context, *connect.Request[v1.SaveManifestRequest]) (*connect.Response[v1.SaveManifestResponse], error)
}

// NewDiscoveryServiceClient constructs a client for the aleph.v1.DiscoveryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDiscoveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DiscoveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &discoveryServiceClient{
		discoverDatabase: connect.NewClient[v1.DiscoverDatabaseRequest, v1.DiscoverDatabaseResponse](
			httpClient,
			baseURL+DiscoveryServiceDiscoverDatabaseProcedure,
			connect.WithSchema(discoveryServiceDiscoverDatabaseMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getManifest: connect.NewClient[v1.GetManifestRequest, v1.GetManifestResponse](
			httpClient,
			baseURL+DiscoveryServiceGetManifestProcedure,
			connect.WithSchema(discoveryServiceGetManifestMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		saveManifest: connect.NewClient[v1.SaveManifestRequest, v1.SaveManifestResponse](
			httpClient,
			baseURL+DiscoveryServiceSaveManifestProcedure,
			connect.WithSchema(discoveryServiceSaveManifestMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// discoveryServiceClient implements DiscoveryServiceClient.
type discoveryServiceClient struct {
	discoverDatabase *connect.Client[v1.DiscoverDatabaseRequest, v1.DiscoverDatabaseResponse]
	getManifest      *connect.Client[v1.GetManifestRequest, v1.GetManifestResponse]
	saveManifest     *connect.Client[v1.SaveManifestRequest, v1.SaveManifestResponse]
}

// DiscoverDatabase calls aleph.v1.DiscoveryService.DiscoverDatabase.
func (c *discoveryServiceClient) DiscoverDatabase(ctx context.Context, req *connect.Request[v1.DiscoverDatabaseRequest]) (*connect.Response[v1.DiscoverDatabaseResponse], error) {
	return c.discoverDatabase.CallUnary(ctx, req)
}

// GetManifest calls aleph.v1.DiscoveryService.GetManifest.
func (c *discoveryServiceClient) GetManifest(ctx context.Context, req *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// SaveManifest calls aleph.v1.DiscoveryService.SaveManifest.
func (c *discoveryServiceClient) SaveManifest(ctx context.Context, req *connect.Request[v1.SaveManifestRequest]) (*connect.Response[v1.SaveManifestResponse], error) {
	return c.saveManifest.CallUnary(ctx, req)
}

// DiscoveryServiceHandler is an implementation of the aleph.v1.DiscoveryService service.
type DiscoveryServiceHandler interface {
	DiscoverDatabase(context.Context, *connect.Request[v1.DiscoverDatabaseRequest]) (*connect.Response[v1.DiscoverDatabaseResponse], error)
	GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error)
	SaveManifest(context.Context, *connect.Request[v1.SaveManifestRequest]) (*connect.Response[v1.SaveManifestResponse], error)
}

// NewDiscoveryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDiscoveryServiceHandler(svc DiscoveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	discoveryServiceDiscoverDatabaseHandler := connect.NewUnaryHandler(
		DiscoveryServiceDiscoverDatabaseProcedure,
		svc.DiscoverDatabase,
		connect.WithSchema(discoveryServiceDiscoverDatabaseMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	discoveryServiceGetManifestHandler := connect.NewUnaryHandler(
		DiscoveryServiceGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(discoveryServiceGetManifestMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	discoveryServiceSaveManifestHandler := connect.NewUnaryHandler(
		DiscoveryServiceSaveManifestProcedure,
		svc.SaveManifest,
		connect.WithSchema(discoveryServiceSaveManifestMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.DiscoveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DiscoveryServiceDiscoverDatabaseProcedure:
			discoveryServiceDiscoverDatabaseHandler.ServeHTTP(w, r)
		case DiscoveryServiceGetManifestProcedure:
			discoveryServiceGetManifestHandler.ServeHTTP(w, r)
		case DiscoveryServiceSaveManifestProcedure:
			discoveryServiceSaveManifestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDiscoveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDiscoveryServiceHandler struct{}

func (UnimplementedDiscoveryServiceHandler) DiscoverDatabase(context.Context, *connect.Request[v1.DiscoverDatabaseRequest]) (*connect.Response[v1.DiscoverDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.DiscoveryService.DiscoverDatabase is not implemented"))
}

func (UnimplementedDiscoveryServiceHandler) GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.DiscoveryService.GetManifest is not implemented"))
}

func (UnimplementedDiscoveryServiceHandler) SaveManifest(context.Context, *connect.Request[v1.SaveManifestRequest]) (*connect.Response[v1.SaveManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.DiscoveryService.SaveManifest is not implemented"))
}
