// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aleph/v1/notification.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "aleph.v1.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceSendWebhookProcedure is the fully-qualified name of the NotificationService's
	// SendWebhook RPC.
	NotificationServiceSendWebhookProcedure = "/aleph.v1.NotificationService/SendWebhook"
	// NotificationServiceListChannelsProcedure is the fully-qualified name of the NotificationService's
	// ListChannels RPC.
	NotificationServiceListChannelsProcedure = "/aleph.v1.NotificationService/ListChannels"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	notificationServiceServiceDescriptor            = v1.File_aleph_v1_notification_proto.Services().ByName("NotificationService")
	notificationServiceSendWebhookMethodDescriptor  = notificationServiceServiceDescriptor.Methods().ByName("SendWebhook")
	notificationServiceListChannelsMethodDescriptor = notificationServiceServiceDescriptor.Methods().ByName("ListChannels")
)

// NotificationServiceClient is a client for the aleph.v1.NotificationService service.
type NotificationServiceClient interface {
	SendWebhook(context.Context, *connect.Request[v1.SendWebhookRequest]) (*connect.Response[v1.SendWebhookResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
}

// NewNotificationServiceClient constructs a client for the aleph.v1.NotificationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &notificationServiceClient{
		sendWebhook: connect.NewClient[v1.SendWebhookRequest, v1.SendWebhookResponse](
			httpClient,
			baseURL+NotificationServiceSendWebhookProcedure,
			connect.WithSchema(notificationServiceSendWebhookMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listChannels: connect.NewClient[v1.ListChannelsRequest, v1.ListChannelsResponse](
			httpClient,
			baseURL+NotificationServiceListChannelsProcedure,
			connect.WithSchema(notificationServiceListChannelsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	sendWebhook  *connect.Client[v1.SendWebhookRequest, v1.SendWebhookResponse]
	listChannels *connect.Client[v1.ListChannelsRequest, v1.ListChannelsResponse]
}

// SendWebhook calls aleph.v1.NotificationService.SendWebhook.
func (c *notificationServiceClient) SendWebhook(ctx context.Context, req *connect.Request[v1.SendWebhookRequest]) (*connect.Response[v1.SendWebhookResponse], error) {
	return c.sendWebhook.CallUnary(ctx, req)
}

// ListChannels calls aleph.v1.NotificationService.ListChannels.
func (c *notificationServiceClient) ListChannels(ctx context.Context, req *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the aleph.v1.NotificationService service.
type NotificationServiceHandler interface {
	SendWebhook(context.Context, *connect.Request[v1.SendWebhookRequest]) (*connect.Response[v1.SendWebhookResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceSendWebhookHandler := connect.NewUnaryHandler(
		NotificationServiceSendWebhookProcedure,
		svc.SendWebhook,
		connect.WithSchema(notificationServiceSendWebhookMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceListChannelsHandler := connect.NewUnaryHandler(
		NotificationServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(notificationServiceListChannelsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceSendWebhookProcedure:
			notificationServiceSendWebhookHandler.ServeHTTP(w, r)
		case NotificationServiceListChannelsProcedure:
			notificationServiceListChannelsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) SendWebhook(context.Context, *connect.Request[v1.SendWebhookRequest]) (*connect.Response[v1.SendWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.NotificationService.SendWebhook is not implemented"))
}

func (UnimplementedNotificationServiceHandler) ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.NotificationService.ListChannels is not implemented"))
}
