// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aleph/v1/query.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QueryServiceName is the fully-qualified name of the QueryService service.
	QueryServiceName = "aleph.v1.QueryService"
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "aleph.v1.ProjectService"
	// IngestionServiceName is the fully-qualified name of the IngestionService service.
	IngestionServiceName = "aleph.v1.IngestionService"
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "aleph.v1.AgentService"
	// SkillServiceName is the fully-qualified name of the SkillService service.
	SkillServiceName = "aleph.v1.SkillService"
	// ToolServiceName is the fully-qualified name of the ToolService service.
	ToolServiceName = "aleph.v1.ToolService"
	// LibraryServiceName is the fully-qualified name of the LibraryService service.
	LibraryServiceName = "aleph.v1.LibraryService"
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "aleph.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QueryServiceExecuteQueryProcedure is the fully-qualified name of the QueryService's ExecuteQuery
	// RPC.
	QueryServiceExecuteQueryProcedure = "/aleph.v1.QueryService/ExecuteQuery"
	// QueryServiceChatProcedure is the fully-qualified name of the QueryService's Chat RPC.
	QueryServiceChatProcedure = "/aleph.v1.QueryService/Chat"
	// QueryServiceGetChatHistoryProcedure is the fully-qualified name of the QueryService's
	// GetChatHistory RPC.
	QueryServiceGetChatHistoryProcedure = "/aleph.v1.QueryService/GetChatHistory"
	// QueryServiceGetDataStatsProcedure is the fully-qualified name of the QueryService's GetDataStats
	// RPC.
	QueryServiceGetDataStatsProcedure = "/aleph.v1.QueryService/GetDataStats"
	// QueryServiceConfirmActionProcedure is the fully-qualified name of the QueryService's
	// ConfirmAction RPC.
	QueryServiceConfirmActionProcedure = "/aleph.v1.QueryService/ConfirmAction"
	// QueryServiceGlobalQueryProcedure is the fully-qualified name of the QueryService's GlobalQuery
	// RPC.
	QueryServiceGlobalQueryProcedure = "/aleph.v1.QueryService/GlobalQuery"
	// QueryServiceGetDataLineageProcedure is the fully-qualified name of the QueryService's
	// GetDataLineage RPC.
	QueryServiceGetDataLineageProcedure = "/aleph.v1.QueryService/GetDataLineage"
	// QueryServiceGetChecksumProcedure is the fully-qualified name of the QueryService's GetChecksum
	// RPC.
	QueryServiceGetChecksumProcedure = "/aleph.v1.QueryService/GetChecksum"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/aleph.v1.ProjectService/ListProjects"
	// ProjectServiceCreateProjectProcedure is the fully-qualified name of the ProjectService's
	// CreateProject RPC.
	ProjectServiceCreateProjectProcedure = "/aleph.v1.ProjectService/CreateProject"
	// ProjectServiceDeleteProjectProcedure is the fully-qualified name of the ProjectService's
	// DeleteProject RPC.
	ProjectServiceDeleteProjectProcedure = "/aleph.v1.ProjectService/DeleteProject"
	// ProjectServiceEmergeOntologyProcedure is the fully-qualified name of the ProjectService's
	// EmergeOntology RPC.
	ProjectServiceEmergeOntologyProcedure = "/aleph.v1.ProjectService/EmergeOntology"
	// ProjectServiceGetOntologyProcedure is the fully-qualified name of the ProjectService's
	// GetOntology RPC.
	ProjectServiceGetOntologyProcedure = "/aleph.v1.ProjectService/GetOntology"
	// ProjectServiceSaveOntologyProcedure is the fully-qualified name of the ProjectService's
	// SaveOntology RPC.
	ProjectServiceSaveOntologyProcedure = "/aleph.v1.ProjectService/SaveOntology"
	// IngestionServiceListTasksProcedure is the fully-qualified name of the IngestionService's
	// ListTasks RPC.
	IngestionServiceListTasksProcedure = "/aleph.v1.IngestionService/ListTasks"
	// IngestionServiceCreateTaskProcedure is the fully-qualified name of the IngestionService's
	// CreateTask RPC.
	IngestionServiceCreateTaskProcedure = "/aleph.v1.IngestionService/CreateTask"
	// IngestionServiceDeleteTaskProcedure is the fully-qualified name of the IngestionService's
	// DeleteTask RPC.
	IngestionServiceDeleteTaskProcedure = "/aleph.v1.IngestionService/DeleteTask"
	// IngestionServiceRunTaskProcedure is the fully-qualified name of the IngestionService's RunTask
	// RPC.
	IngestionServiceRunTaskProcedure = "/aleph.v1.IngestionService/RunTask"
	// IngestionServiceGetTaskLogsProcedure is the fully-qualified name of the IngestionService's
	// GetTaskLogs RPC.
	IngestionServiceGetTaskLogsProcedure = "/aleph.v1.IngestionService/GetTaskLogs"
	// IngestionServiceGetProgressProcedure is the fully-qualified name of the IngestionService's
	// GetProgress RPC.
	IngestionServiceGetProgressProcedure = "/aleph.v1.IngestionService/GetProgress"
	// AgentServiceListAgentsProcedure is the fully-qualified name of the AgentService's ListAgents RPC.
	AgentServiceListAgentsProcedure = "/aleph.v1.AgentService/ListAgents"
	// AgentServiceCreateAgentProcedure is the fully-qualified name of the AgentService's CreateAgent
	// RPC.
	AgentServiceCreateAgentProcedure = "/aleph.v1.AgentService/CreateAgent"
	// AgentServiceDeleteAgentProcedure is the fully-qualified name of the AgentService's DeleteAgent
	// RPC.
	AgentServiceDeleteAgentProcedure = "/aleph.v1.AgentService/DeleteAgent"
	// AgentServiceUpdateAgentProcedure is the fully-qualified name of the AgentService's UpdateAgent
	// RPC.
	AgentServiceUpdateAgentProcedure = "/aleph.v1.AgentService/UpdateAgent"
	// AgentServiceListModelsProcedure is the fully-qualified name of the AgentService's ListModels RPC.
	AgentServiceListModelsProcedure = "/aleph.v1.AgentService/ListModels"
	// SkillServiceListSkillsProcedure is the fully-qualified name of the SkillService's ListSkills RPC.
	SkillServiceListSkillsProcedure = "/aleph.v1.SkillService/ListSkills"
	// SkillServiceCreateSkillProcedure is the fully-qualified name of the SkillService's CreateSkill
	// RPC.
	SkillServiceCreateSkillProcedure = "/aleph.v1.SkillService/CreateSkill"
	// SkillServiceUpdateSkillProcedure is the fully-qualified name of the SkillService's UpdateSkill
	// RPC.
	SkillServiceUpdateSkillProcedure = "/aleph.v1.SkillService/UpdateSkill"
	// SkillServiceDeleteSkillProcedure is the fully-qualified name of the SkillService's DeleteSkill
	// RPC.
	SkillServiceDeleteSkillProcedure = "/aleph.v1.SkillService/DeleteSkill"
	// ToolServiceListToolsProcedure is the fully-qualified name of the ToolService's ListTools RPC.
	ToolServiceListToolsProcedure = "/aleph.v1.ToolService/ListTools"
	// ToolServiceCreateToolProcedure is the fully-qualified name of the ToolService's CreateTool RPC.
	ToolServiceCreateToolProcedure = "/aleph.v1.ToolService/CreateTool"
	// ToolServiceUpdateToolProcedure is the fully-qualified name of the ToolService's UpdateTool RPC.
	ToolServiceUpdateToolProcedure = "/aleph.v1.ToolService/UpdateTool"
	// ToolServiceDeleteToolProcedure is the fully-qualified name of the ToolService's DeleteTool RPC.
	ToolServiceDeleteToolProcedure = "/aleph.v1.ToolService/DeleteTool"
	// LibraryServiceListAssetsProcedure is the fully-qualified name of the LibraryService's ListAssets
	// RPC.
	LibraryServiceListAssetsProcedure = "/aleph.v1.LibraryService/ListAssets"
	// LibraryServiceGetAssetContentProcedure is the fully-qualified name of the LibraryService's
	// GetAssetContent RPC.
	LibraryServiceGetAssetContentProcedure = "/aleph.v1.LibraryService/GetAssetContent"
	// LibraryServiceDeleteAssetProcedure is the fully-qualified name of the LibraryService's
	// DeleteAsset RPC.
	LibraryServiceDeleteAssetProcedure = "/aleph.v1.LibraryService/DeleteAsset"
	// LibraryServiceGeneratePdfProcedure is the fully-qualified name of the LibraryService's
	// GeneratePdf RPC.
	LibraryServiceGeneratePdfProcedure = "/aleph.v1.LibraryService/GeneratePdf"
	// LibraryServiceUploadAssetProcedure is the fully-qualified name of the LibraryService's
	// UploadAsset RPC.
	LibraryServiceUploadAssetProcedure = "/aleph.v1.LibraryService/UploadAsset"
	// AuthServiceListApiKeysProcedure is the fully-qualified name of the AuthService's ListApiKeys RPC.
	AuthServiceListApiKeysProcedure = "/aleph.v1.AuthService/ListApiKeys"
	// AuthServiceCreateApiKeyProcedure is the fully-qualified name of the AuthService's CreateApiKey
	// RPC.
	AuthServiceCreateApiKeyProcedure = "/aleph.v1.AuthService/CreateApiKey"
	// AuthServiceDeleteApiKeyProcedure is the fully-qualified name of the AuthService's DeleteApiKey
	// RPC.
	AuthServiceDeleteApiKeyProcedure = "/aleph.v1.AuthService/DeleteApiKey"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	queryServiceServiceDescriptor                 = v1.File_aleph_v1_query_proto.Services().ByName("QueryService")
	queryServiceExecuteQueryMethodDescriptor      = queryServiceServiceDescriptor.Methods().ByName("ExecuteQuery")
	queryServiceChatMethodDescriptor              = queryServiceServiceDescriptor.Methods().ByName("Chat")
	queryServiceGetChatHistoryMethodDescriptor    = queryServiceServiceDescriptor.Methods().ByName("GetChatHistory")
	queryServiceGetDataStatsMethodDescriptor      = queryServiceServiceDescriptor.Methods().ByName("GetDataStats")
	queryServiceConfirmActionMethodDescriptor     = queryServiceServiceDescriptor.Methods().ByName("ConfirmAction")
	queryServiceGlobalQueryMethodDescriptor       = queryServiceServiceDescriptor.Methods().ByName("GlobalQuery")
	queryServiceGetDataLineageMethodDescriptor    = queryServiceServiceDescriptor.Methods().ByName("GetDataLineage")
	queryServiceGetChecksumMethodDescriptor       = queryServiceServiceDescriptor.Methods().ByName("GetChecksum")
	projectServiceServiceDescriptor               = v1.File_aleph_v1_query_proto.Services().ByName("ProjectService")
	projectServiceListProjectsMethodDescriptor    = projectServiceServiceDescriptor.Methods().ByName("ListProjects")
	projectServiceCreateProjectMethodDescriptor   = projectServiceServiceDescriptor.Methods().ByName("CreateProject")
	projectServiceDeleteProjectMethodDescriptor   = projectServiceServiceDescriptor.Methods().ByName("DeleteProject")
	projectServiceEmergeOntologyMethodDescriptor  = projectServiceServiceDescriptor.Methods().ByName("EmergeOntology")
	projectServiceGetOntologyMethodDescriptor     = projectServiceServiceDescriptor.Methods().ByName("GetOntology")
	projectServiceSaveOntologyMethodDescriptor    = projectServiceServiceDescriptor.Methods().ByName("SaveOntology")
	ingestionServiceServiceDescriptor             = v1.File_aleph_v1_query_proto.Services().ByName("IngestionService")
	ingestionServiceListTasksMethodDescriptor     = ingestionServiceServiceDescriptor.Methods().ByName("ListTasks")
	ingestionServiceCreateTaskMethodDescriptor    = ingestionServiceServiceDescriptor.Methods().ByName("CreateTask")
	ingestionServiceDeleteTaskMethodDescriptor    = ingestionServiceServiceDescriptor.Methods().ByName("DeleteTask")
	ingestionServiceRunTaskMethodDescriptor       = ingestionServiceServiceDescriptor.Methods().ByName("RunTask")
	ingestionServiceGetTaskLogsMethodDescriptor   = ingestionServiceServiceDescriptor.Methods().ByName("GetTaskLogs")
	ingestionServiceGetProgressMethodDescriptor   = ingestionServiceServiceDescriptor.Methods().ByName("GetProgress")
	agentServiceServiceDescriptor                 = v1.File_aleph_v1_query_proto.Services().ByName("AgentService")
	agentServiceListAgentsMethodDescriptor        = agentServiceServiceDescriptor.Methods().ByName("ListAgents")
	agentServiceCreateAgentMethodDescriptor       = agentServiceServiceDescriptor.Methods().ByName("CreateAgent")
	agentServiceDeleteAgentMethodDescriptor       = agentServiceServiceDescriptor.Methods().ByName("DeleteAgent")
	agentServiceUpdateAgentMethodDescriptor       = agentServiceServiceDescriptor.Methods().ByName("UpdateAgent")
	agentServiceListModelsMethodDescriptor        = agentServiceServiceDescriptor.Methods().ByName("ListModels")
	skillServiceServiceDescriptor                 = v1.File_aleph_v1_query_proto.Services().ByName("SkillService")
	skillServiceListSkillsMethodDescriptor        = skillServiceServiceDescriptor.Methods().ByName("ListSkills")
	skillServiceCreateSkillMethodDescriptor       = skillServiceServiceDescriptor.Methods().ByName("CreateSkill")
	skillServiceUpdateSkillMethodDescriptor       = skillServiceServiceDescriptor.Methods().ByName("UpdateSkill")
	skillServiceDeleteSkillMethodDescriptor       = skillServiceServiceDescriptor.Methods().ByName("DeleteSkill")
	toolServiceServiceDescriptor                  = v1.File_aleph_v1_query_proto.Services().ByName("ToolService")
	toolServiceListToolsMethodDescriptor          = toolServiceServiceDescriptor.Methods().ByName("ListTools")
	toolServiceCreateToolMethodDescriptor         = toolServiceServiceDescriptor.Methods().ByName("CreateTool")
	toolServiceUpdateToolMethodDescriptor         = toolServiceServiceDescriptor.Methods().ByName("UpdateTool")
	toolServiceDeleteToolMethodDescriptor         = toolServiceServiceDescriptor.Methods().ByName("DeleteTool")
	libraryServiceServiceDescriptor               = v1.File_aleph_v1_query_proto.Services().ByName("LibraryService")
	libraryServiceListAssetsMethodDescriptor      = libraryServiceServiceDescriptor.Methods().ByName("ListAssets")
	libraryServiceGetAssetContentMethodDescriptor = libraryServiceServiceDescriptor.Methods().ByName("GetAssetContent")
	libraryServiceDeleteAssetMethodDescriptor     = libraryServiceServiceDescriptor.Methods().ByName("DeleteAsset")
	libraryServiceGeneratePdfMethodDescriptor     = libraryServiceServiceDescriptor.Methods().ByName("GeneratePdf")
	libraryServiceUploadAssetMethodDescriptor     = libraryServiceServiceDescriptor.Methods().ByName("UploadAsset")
	authServiceServiceDescriptor                  = v1.File_aleph_v1_query_proto.Services().ByName("AuthService")
	authServiceListApiKeysMethodDescriptor        = authServiceServiceDescriptor.Methods().ByName("ListApiKeys")
	authServiceCreateApiKeyMethodDescriptor       = authServiceServiceDescriptor.Methods().ByName("CreateApiKey")
	authServiceDeleteApiKeyMethodDescriptor       = authServiceServiceDescriptor.Methods().ByName("DeleteApiKey")
)

// QueryServiceClient is a client for the aleph.v1.QueryService service.
type QueryServiceClient interface {
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	Chat(context.Context, *connect.Request[v1.ChatRequest]) (*connect.ServerStreamForClient[v1.ChatResponse], error)
	GetChatHistory(context.Context, *connect.Request[v1.GetChatHistoryRequest]) (*connect.Response[v1.GetChatHistoryResponse], error)
	GetDataStats(context.Context, *connect.Request[v1.GetDataStatsRequest]) (*connect.Response[v1.GetDataStatsResponse], error)
	ConfirmAction(context.Context, *connect.Request[v1.ConfirmActionRequest]) (*connect.Response[v1.ConfirmActionResponse], error)
	GlobalQuery(context.Context, *connect.Request[v1.GlobalQueryRequest]) (*connect.Response[v1.GlobalQueryResponse], error)
	GetDataLineage(context.Context, *connect.Request[v1.GetDataLineageRequest]) (*connect.Response[v1.GetDataLineageResponse], error)
	GetChecksum(context.Context, *connect.Request[v1.GetChecksumRequest]) (*connect.Response[v1.GetChecksumResponse], error)
}

// NewQueryServiceClient constructs a client for the aleph.v1.QueryService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QueryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &queryServiceClient{
		executeQuery: connect.NewClient[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse](
			httpClient,
			baseURL+QueryServiceExecuteQueryProcedure,
			connect.WithSchema(queryServiceExecuteQueryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		chat: connect.NewClient[v1.ChatRequest, v1.ChatResponse](
			httpClient,
			baseURL+QueryServiceChatProcedure,
			connect.WithSchema(queryServiceChatMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getChatHistory: connect.NewClient[v1.GetChatHistoryRequest, v1.GetChatHistoryResponse](
			httpClient,
			baseURL+QueryServiceGetChatHistoryProcedure,
			connect.WithSchema(queryServiceGetChatHistoryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDataStats: connect.NewClient[v1.GetDataStatsRequest, v1.GetDataStatsResponse](
			httpClient,
			baseURL+QueryServiceGetDataStatsProcedure,
			connect.WithSchema(queryServiceGetDataStatsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		confirmAction: connect.NewClient[v1.ConfirmActionRequest, v1.ConfirmActionResponse](
			httpClient,
			baseURL+QueryServiceConfirmActionProcedure,
			connect.WithSchema(queryServiceConfirmActionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		globalQuery: connect.NewClient[v1.GlobalQueryRequest, v1.GlobalQueryResponse](
			httpClient,
			baseURL+QueryServiceGlobalQueryProcedure,
			connect.WithSchema(queryServiceGlobalQueryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDataLineage: connect.NewClient[v1.GetDataLineageRequest, v1.GetDataLineageResponse](
			httpClient,
			baseURL+QueryServiceGetDataLineageProcedure,
			connect.WithSchema(queryServiceGetDataLineageMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getChecksum: connect.NewClient[v1.GetChecksumRequest, v1.GetChecksumResponse](
			httpClient,
			baseURL+QueryServiceGetChecksumProcedure,
			connect.WithSchema(queryServiceGetChecksumMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// queryServiceClient implements QueryServiceClient.
type queryServiceClient struct {
	executeQuery   *connect.Client[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse]
	chat           *connect.Client[v1.ChatRequest, v1.ChatResponse]
	getChatHistory *connect.Client[v1.GetChatHistoryRequest, v1.GetChatHistoryResponse]
	getDataStats   *connect.Client[v1.GetDataStatsRequest, v1.GetDataStatsResponse]
	confirmAction  *connect.Client[v1.ConfirmActionRequest, v1.ConfirmActionResponse]
	globalQuery    *connect.Client[v1.GlobalQueryRequest, v1.GlobalQueryResponse]
	getDataLineage *connect.Client[v1.GetDataLineageRequest, v1.GetDataLineageResponse]
	getChecksum    *connect.Client[v1.GetChecksumRequest, v1.GetChecksumResponse]
}

// ExecuteQuery calls aleph.v1.QueryService.ExecuteQuery.
func (c *queryServiceClient) ExecuteQuery(ctx context.Context, req *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return c.executeQuery.CallUnary(ctx, req)
}

// Chat calls aleph.v1.QueryService.Chat.
func (c *queryServiceClient) Chat(ctx context.Context, req *connect.Request[v1.ChatRequest]) (*connect.ServerStreamForClient[v1.ChatResponse], error) {
	return c.chat.CallServerStream(ctx, req)
}

// GetChatHistory calls aleph.v1.QueryService.GetChatHistory.
func (c *queryServiceClient) GetChatHistory(ctx context.Context, req *connect.Request[v1.GetChatHistoryRequest]) (*connect.Response[v1.GetChatHistoryResponse], error) {
	return c.getChatHistory.CallUnary(ctx, req)
}

// GetDataStats calls aleph.v1.QueryService.GetDataStats.
func (c *queryServiceClient) GetDataStats(ctx context.Context, req *connect.Request[v1.GetDataStatsRequest]) (*connect.Response[v1.GetDataStatsResponse], error) {
	return c.getDataStats.CallUnary(ctx, req)
}

// ConfirmAction calls aleph.v1.QueryService.ConfirmAction.
func (c *queryServiceClient) ConfirmAction(ctx context.Context, req *connect.Request[v1.ConfirmActionRequest]) (*connect.Response[v1.ConfirmActionResponse], error) {
	return c.confirmAction.CallUnary(ctx, req)
}

// GlobalQuery calls aleph.v1.QueryService.GlobalQuery.
func (c *queryServiceClient) GlobalQuery(ctx context.Context, req *connect.Request[v1.GlobalQueryRequest]) (*connect.Response[v1.GlobalQueryResponse], error) {
	return c.globalQuery.CallUnary(ctx, req)
}

// GetDataLineage calls aleph.v1.QueryService.GetDataLineage.
func (c *queryServiceClient) GetDataLineage(ctx context.Context, req *connect.Request[v1.GetDataLineageRequest]) (*connect.Response[v1.GetDataLineageResponse], error) {
	return c.getDataLineage.CallUnary(ctx, req)
}

// GetChecksum calls aleph.v1.QueryService.GetChecksum.
func (c *queryServiceClient) GetChecksum(ctx context.Context, req *connect.Request[v1.GetChecksumRequest]) (*connect.Response[v1.GetChecksumResponse], error) {
	return c.getChecksum.CallUnary(ctx, req)
}

// QueryServiceHandler is an implementation of the aleph.v1.QueryService service.
type QueryServiceHandler interface {
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	Chat(context.Context, *connect.Request[v1.ChatRequest], *connect.ServerStream[v1.ChatResponse]) error
	GetChatHistory(context.Context, *connect.Request[v1.GetChatHistoryRequest]) (*connect.Response[v1.GetChatHistoryResponse], error)
	GetDataStats(context.Context, *connect.Request[v1.GetDataStatsRequest]) (*connect.Response[v1.GetDataStatsResponse], error)
	ConfirmAction(context.Context, *connect.Request[v1.ConfirmActionRequest]) (*connect.Response[v1.ConfirmActionResponse], error)
	GlobalQuery(context.Context, *connect.Request[v1.GlobalQueryRequest]) (*connect.Response[v1.GlobalQueryResponse], error)
	GetDataLineage(context.Context, *connect.Request[v1.GetDataLineageRequest]) (*connect.Response[v1.GetDataLineageResponse], error)
	GetChecksum(context.Context, *connect.Request[v1.GetChecksumRequest]) (*connect.Response[v1.GetChecksumResponse], error)
}

// NewQueryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQueryServiceHandler(svc QueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	queryServiceExecuteQueryHandler := connect.NewUnaryHandler(
		QueryServiceExecuteQueryProcedure,
		svc.ExecuteQuery,
		connect.WithSchema(queryServiceExecuteQueryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceChatHandler := connect.NewServerStreamHandler(
		QueryServiceChatProcedure,
		svc.Chat,
		connect.WithSchema(queryServiceChatMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceGetChatHistoryHandler := connect.NewUnaryHandler(
		QueryServiceGetChatHistoryProcedure,
		svc.GetChatHistory,
		connect.WithSchema(queryServiceGetChatHistoryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceGetDataStatsHandler := connect.NewUnaryHandler(
		QueryServiceGetDataStatsProcedure,
		svc.GetDataStats,
		connect.WithSchema(queryServiceGetDataStatsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceConfirmActionHandler := connect.NewUnaryHandler(
		QueryServiceConfirmActionProcedure,
		svc.ConfirmAction,
		connect.WithSchema(queryServiceConfirmActionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceGlobalQueryHandler := connect.NewUnaryHandler(
		QueryServiceGlobalQueryProcedure,
		svc.GlobalQuery,
		connect.WithSchema(queryServiceGlobalQueryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceGetDataLineageHandler := connect.NewUnaryHandler(
		QueryServiceGetDataLineageProcedure,
		svc.GetDataLineage,
		connect.WithSchema(queryServiceGetDataLineageMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceGetChecksumHandler := connect.NewUnaryHandler(
		QueryServiceGetChecksumProcedure,
		svc.GetChecksum,
		connect.WithSchema(queryServiceGetChecksumMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.QueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QueryServiceExecuteQueryProcedure:
			queryServiceExecuteQueryHandler.ServeHTTP(w, r)
		case QueryServiceChatProcedure:
			queryServiceChatHandler.ServeHTTP(w, r)
		case QueryServiceGetChatHistoryProcedure:
			queryServiceGetChatHistoryHandler.ServeHTTP(w, r)
		case QueryServiceGetDataStatsProcedure:
			queryServiceGetDataStatsHandler.ServeHTTP(w, r)
		case QueryServiceConfirmActionProcedure:
			queryServiceConfirmActionHandler.ServeHTTP(w, r)
		case QueryServiceGlobalQueryProcedure:
			queryServiceGlobalQueryHandler.ServeHTTP(w, r)
		case QueryServiceGetDataLineageProcedure:
			queryServiceGetDataLineageHandler.ServeHTTP(w, r)
		case QueryServiceGetChecksumProcedure:
			queryServiceGetChecksumHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQueryServiceHandler struct{}

func (UnimplementedQueryServiceHandler) ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.ExecuteQuery is not implemented"))
}

func (UnimplementedQueryServiceHandler) Chat(context.Context, *connect.Request[v1.ChatRequest], *connect.ServerStream[v1.ChatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.Chat is not implemented"))
}

func (UnimplementedQueryServiceHandler) GetChatHistory(context.Context, *connect.Request[v1.GetChatHistoryRequest]) (*connect.Response[v1.GetChatHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.GetChatHistory is not implemented"))
}

func (UnimplementedQueryServiceHandler) GetDataStats(context.Context, *connect.Request[v1.GetDataStatsRequest]) (*connect.Response[v1.GetDataStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.GetDataStats is not implemented"))
}

func (UnimplementedQueryServiceHandler) ConfirmAction(context.Context, *connect.Request[v1.ConfirmActionRequest]) (*connect.Response[v1.ConfirmActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.ConfirmAction is not implemented"))
}

func (UnimplementedQueryServiceHandler) GlobalQuery(context.Context, *connect.Request[v1.GlobalQueryRequest]) (*connect.Response[v1.GlobalQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.GlobalQuery is not implemented"))
}

func (UnimplementedQueryServiceHandler) GetDataLineage(context.Context, *connect.Request[v1.GetDataLineageRequest]) (*connect.Response[v1.GetDataLineageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.GetDataLineage is not implemented"))
}

func (UnimplementedQueryServiceHandler) GetChecksum(context.Context, *connect.Request[v1.GetChecksumRequest]) (*connect.Response[v1.GetChecksumResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.QueryService.GetChecksum is not implemented"))
}

// ProjectServiceClient is a client for the aleph.v1.ProjectService service.
type ProjectServiceClient interface {
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error)
	EmergeOntology(context.Context, *connect.Request[v1.EmergeOntologyRequest]) (*connect.Response[v1.EmergeOntologyResponse], error)
	GetOntology(context.Context, *connect.Request[v1.GetOntologyRequest]) (*connect.Response[v1.GetOntologyResponse], error)
	SaveOntology(context.Context, *connect.Request[v1.SaveOntologyRequest]) (*connect.Response[v1.SaveOntologyResponse], error)
}

// NewProjectServiceClient constructs a client for the aleph.v1.ProjectService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &projectServiceClient{
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceListProjectsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+ProjectServiceCreateProjectProcedure,
			connect.WithSchema(projectServiceCreateProjectMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[v1.DeleteProjectRequest, v1.DeleteProjectResponse](
			httpClient,
			baseURL+ProjectServiceDeleteProjectProcedure,
			connect.WithSchema(projectServiceDeleteProjectMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		emergeOntology: connect.NewClient[v1.EmergeOntologyRequest, v1.EmergeOntologyResponse](
			httpClient,
			baseURL+ProjectServiceEmergeOntologyProcedure,
			connect.WithSchema(projectServiceEmergeOntologyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getOntology: connect.NewClient[v1.GetOntologyRequest, v1.GetOntologyResponse](
			httpClient,
			baseURL+ProjectServiceGetOntologyProcedure,
			connect.WithSchema(projectServiceGetOntologyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		saveOntology: connect.NewClient[v1.SaveOntologyRequest, v1.SaveOntologyResponse](
			httpClient,
			baseURL+ProjectServiceSaveOntologyProcedure,
			connect.WithSchema(projectServiceSaveOntologyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	listProjects   *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	createProject  *connect.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	deleteProject  *connect.Client[v1.DeleteProjectRequest, v1.DeleteProjectResponse]
	emergeOntology *connect.Client[v1.EmergeOntologyRequest, v1.EmergeOntologyResponse]
	getOntology    *connect.Client[v1.GetOntologyRequest, v1.GetOntologyResponse]
	saveOntology   *connect.Client[v1.SaveOntologyRequest, v1.SaveOntologyResponse]
}

// ListProjects calls aleph.v1.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// CreateProject calls aleph.v1.ProjectService.CreateProject.
func (c *projectServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// DeleteProject calls aleph.v1.ProjectService.DeleteProject.
func (c *projectServiceClient) DeleteProject(ctx context.Context, req *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// EmergeOntology calls aleph.v1.ProjectService.EmergeOntology.
func (c *projectServiceClient) EmergeOntology(ctx context.Context, req *connect.Request[v1.EmergeOntologyRequest]) (*connect.Response[v1.EmergeOntologyResponse], error) {
	return c.emergeOntology.CallUnary(ctx, req)
}

// GetOntology calls aleph.v1.ProjectService.GetOntology.
func (c *projectServiceClient) GetOntology(ctx context.Context, req *connect.Request[v1.GetOntologyRequest]) (*connect.Response[v1.GetOntologyResponse], error) {
	return c.getOntology.CallUnary(ctx, req)
}

// SaveOntology calls aleph.v1.ProjectService.SaveOntology.
func (c *projectServiceClient) SaveOntology(ctx context.Context, req *connect.Request[v1.SaveOntologyRequest]) (*connect.Response[v1.SaveOntologyResponse], error) {
	return c.saveOntology.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the aleph.v1.ProjectService service.
type ProjectServiceHandler interface {
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error)
	EmergeOntology(context.Context, *connect.Request[v1.EmergeOntologyRequest]) (*connect.Response[v1.EmergeOntologyResponse], error)
	GetOntology(context.Context, *connect.Request[v1.GetOntologyRequest]) (*connect.Response[v1.GetOntologyResponse], error)
	SaveOntology(context.Context, *connect.Request[v1.SaveOntologyRequest]) (*connect.Response[v1.SaveOntologyResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceListProjectsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(projectServiceCreateProjectMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceDeleteProjectHandler := connect.NewUnaryHandler(
		ProjectServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(projectServiceDeleteProjectMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceEmergeOntologyHandler := connect.NewUnaryHandler(
		ProjectServiceEmergeOntologyProcedure,
		svc.EmergeOntology,
		connect.WithSchema(projectServiceEmergeOntologyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetOntologyHandler := connect.NewUnaryHandler(
		ProjectServiceGetOntologyProcedure,
		svc.GetOntology,
		connect.WithSchema(projectServiceGetOntologyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceSaveOntologyHandler := connect.NewUnaryHandler(
		ProjectServiceSaveOntologyProcedure,
		svc.SaveOntology,
		connect.WithSchema(projectServiceSaveOntologyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceCreateProjectProcedure:
			projectServiceCreateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceDeleteProjectProcedure:
			projectServiceDeleteProjectHandler.ServeHTTP(w, r)
		case ProjectServiceEmergeOntologyProcedure:
			projectServiceEmergeOntologyHandler.ServeHTTP(w, r)
		case ProjectServiceGetOntologyProcedure:
			projectServiceGetOntologyHandler.ServeHTTP(w, r)
		case ProjectServiceSaveOntologyProcedure:
			projectServiceSaveOntologyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ProjectService.CreateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ProjectService.DeleteProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) EmergeOntology(context.Context, *connect.Request[v1.EmergeOntologyRequest]) (*connect.Response[v1.EmergeOntologyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ProjectService.EmergeOntology is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetOntology(context.Context, *connect.Request[v1.GetOntologyRequest]) (*connect.Response[v1.GetOntologyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ProjectService.GetOntology is not implemented"))
}

func (UnimplementedProjectServiceHandler) SaveOntology(context.Context, *connect.Request[v1.SaveOntologyRequest]) (*connect.Response[v1.SaveOntologyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ProjectService.SaveOntology is not implemented"))
}

// IngestionServiceClient is a client for the aleph.v1.IngestionService service.
type IngestionServiceClient interface {
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error)
	RunTask(context.Context, *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error)
	GetTaskLogs(context.Context, *connect.Request[v1.GetTaskLogsRequest]) (*connect.Response[v1.GetTaskLogsResponse], error)
	GetProgress(context.Context, *connect.Request[v1.GetProgressRequest]) (*connect.Response[v1.GetProgressResponse], error)
}

// NewIngestionServiceClient constructs a client for the aleph.v1.IngestionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngestionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngestionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &ingestionServiceClient{
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+IngestionServiceListTasksProcedure,
			connect.WithSchema(ingestionServiceListTasksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+IngestionServiceCreateTaskProcedure,
			connect.WithSchema(ingestionServiceCreateTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteTask: connect.NewClient[v1.DeleteTaskRequest, v1.DeleteTaskResponse](
			httpClient,
			baseURL+IngestionServiceDeleteTaskProcedure,
			connect.WithSchema(ingestionServiceDeleteTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		runTask: connect.NewClient[v1.RunTaskRequest, v1.RunTaskResponse](
			httpClient,
			baseURL+IngestionServiceRunTaskProcedure,
			connect.WithSchema(ingestionServiceRunTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTaskLogs: connect.NewClient[v1.GetTaskLogsRequest, v1.GetTaskLogsResponse](
			httpClient,
			baseURL+IngestionServiceGetTaskLogsProcedure,
			connect.WithSchema(ingestionServiceGetTaskLogsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getProgress: connect.NewClient[v1.GetProgressRequest, v1.GetProgressResponse](
			httpClient,
			baseURL+IngestionServiceGetProgressProcedure,
			connect.WithSchema(ingestionServiceGetProgressMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingestionServiceClient implements IngestionServiceClient.
type ingestionServiceClient struct {
	listTasks   *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	createTask  *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	deleteTask  *connect.Client[v1.DeleteTaskRequest, v1.DeleteTaskResponse]
	runTask     *connect.Client[v1.RunTaskRequest, v1.RunTaskResponse]
	getTaskLogs *connect.Client[v1.GetTaskLogsRequest, v1.GetTaskLogsResponse]
	getProgress *connect.Client[v1.GetProgressRequest, v1.GetProgressResponse]
}

// ListTasks calls aleph.v1.IngestionService.ListTasks.
func (c *ingestionServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// CreateTask calls aleph.v1.IngestionService.CreateTask.
func (c *ingestionServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// DeleteTask calls aleph.v1.IngestionService.DeleteTask.
func (c *ingestionServiceClient) DeleteTask(ctx context.Context, req *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return c.deleteTask.CallUnary(ctx, req)
}

// RunTask calls aleph.v1.IngestionService.RunTask.
func (c *ingestionServiceClient) RunTask(ctx context.Context, req *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error) {
	return c.runTask.CallUnary(ctx, req)
}

// GetTaskLogs calls aleph.v1.IngestionService.GetTaskLogs.
func (c *ingestionServiceClient) GetTaskLogs(ctx context.Context, req *connect.Request[v1.GetTaskLogsRequest]) (*connect.Response[v1.GetTaskLogsResponse], error) {
	return c.getTaskLogs.CallUnary(ctx, req)
}

// GetProgress calls aleph.v1.IngestionService.GetProgress.
func (c *ingestionServiceClient) GetProgress(ctx context.Context, req *connect.Request[v1.GetProgressRequest]) (*connect.Response[v1.GetProgressResponse], error) {
	return c.getProgress.CallUnary(ctx, req)
}

// IngestionServiceHandler is an implementation of the aleph.v1.IngestionService service.
type IngestionServiceHandler interface {
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error)
	RunTask(context.Context, *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error)
	GetTaskLogs(context.Context, *connect.Request[v1.GetTaskLogsRequest]) (*connect.Response[v1.GetTaskLogsResponse], error)
	GetProgress(context.Context, *connect.Request[v1.GetProgressRequest]) (*connect.Response[v1.GetProgressResponse], error)
}

// NewIngestionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngestionServiceHandler(svc IngestionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingestionServiceListTasksHandler := connect.NewUnaryHandler(
		IngestionServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(ingestionServiceListTasksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ingestionServiceCreateTaskHandler := connect.NewUnaryHandler(
		IngestionServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(ingestionServiceCreateTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ingestionServiceDeleteTaskHandler := connect.NewUnaryHandler(
		IngestionServiceDeleteTaskProcedure,
		svc.DeleteTask,
		connect.WithSchema(ingestionServiceDeleteTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ingestionServiceRunTaskHandler := connect.NewUnaryHandler(
		IngestionServiceRunTaskProcedure,
		svc.RunTask,
		connect.WithSchema(ingestionServiceRunTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ingestionServiceGetTaskLogsHandler := connect.NewUnaryHandler(
		IngestionServiceGetTaskLogsProcedure,
		svc.GetTaskLogs,
		connect.WithSchema(ingestionServiceGetTaskLogsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ingestionServiceGetProgressHandler := connect.NewUnaryHandler(
		IngestionServiceGetProgressProcedure,
		svc.GetProgress,
		connect.WithSchema(ingestionServiceGetProgressMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.IngestionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngestionServiceListTasksProcedure:
			ingestionServiceListTasksHandler.ServeHTTP(w, r)
		case IngestionServiceCreateTaskProcedure:
			ingestionServiceCreateTaskHandler.ServeHTTP(w, r)
		case IngestionServiceDeleteTaskProcedure:
			ingestionServiceDeleteTaskHandler.ServeHTTP(w, r)
		case IngestionServiceRunTaskProcedure:
			ingestionServiceRunTaskHandler.ServeHTTP(w, r)
		case IngestionServiceGetTaskLogsProcedure:
			ingestionServiceGetTaskLogsHandler.ServeHTTP(w, r)
		case IngestionServiceGetProgressProcedure:
			ingestionServiceGetProgressHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngestionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIngestionServiceHandler struct{}

func (UnimplementedIngestionServiceHandler) ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.IngestionService.ListTasks is not implemented"))
}

func (UnimplementedIngestionServiceHandler) CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.IngestionService.CreateTask is not implemented"))
}

func (UnimplementedIngestionServiceHandler) DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.IngestionService.DeleteTask is not implemented"))
}

func (UnimplementedIngestionServiceHandler) RunTask(context.Context, *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.IngestionService.RunTask is not implemented"))
}

func (UnimplementedIngestionServiceHandler) GetTaskLogs(context.Context, *connect.Request[v1.GetTaskLogsRequest]) (*connect.Response[v1.GetTaskLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.IngestionService.GetTaskLogs is not implemented"))
}

func (UnimplementedIngestionServiceHandler) GetProgress(context.Context, *connect.Request[v1.GetProgressRequest]) (*connect.Response[v1.GetProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.IngestionService.GetProgress is not implemented"))
}

// AgentServiceClient is a client for the aleph.v1.AgentService service.
type AgentServiceClient interface {
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error)
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
}

// NewAgentServiceClient constructs a client for the aleph.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &agentServiceClient{
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+AgentServiceListAgentsProcedure,
			connect.WithSchema(agentServiceListAgentsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createAgent: connect.NewClient[v1.CreateAgentRequest, v1.CreateAgentResponse](
			httpClient,
			baseURL+AgentServiceCreateAgentProcedure,
			connect.WithSchema(agentServiceCreateAgentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[v1.DeleteAgentRequest, v1.DeleteAgentResponse](
			httpClient,
			baseURL+AgentServiceDeleteAgentProcedure,
			connect.WithSchema(agentServiceDeleteAgentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[v1.UpdateAgentRequest, v1.UpdateAgentResponse](
			httpClient,
			baseURL+AgentServiceUpdateAgentProcedure,
			connect.WithSchema(agentServiceUpdateAgentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+AgentServiceListModelsProcedure,
			connect.WithSchema(agentServiceListModelsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	listAgents  *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	createAgent *connect.Client[v1.CreateAgentRequest, v1.CreateAgentResponse]
	deleteAgent *connect.Client[v1.DeleteAgentRequest, v1.DeleteAgentResponse]
	updateAgent *connect.Client[v1.UpdateAgentRequest, v1.UpdateAgentResponse]
	listModels  *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
}

// ListAgents calls aleph.v1.AgentService.ListAgents.
func (c *agentServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// CreateAgent calls aleph.v1.AgentService.CreateAgent.
func (c *agentServiceClient) CreateAgent(ctx context.Context, req *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// DeleteAgent calls aleph.v1.AgentService.DeleteAgent.
func (c *agentServiceClient) DeleteAgent(ctx context.Context, req *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// UpdateAgent calls aleph.v1.AgentService.UpdateAgent.
func (c *agentServiceClient) UpdateAgent(ctx context.Context, req *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

// ListModels calls aleph.v1.AgentService.ListModels.
func (c *agentServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the aleph.v1.AgentService service.
type AgentServiceHandler interface {
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error)
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceListAgentsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentServiceListAgentsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCreateAgentHandler := connect.NewUnaryHandler(
		AgentServiceCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(agentServiceCreateAgentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteAgentHandler := connect.NewUnaryHandler(
		AgentServiceDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(agentServiceDeleteAgentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateAgentHandler := connect.NewUnaryHandler(
		AgentServiceUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(agentServiceUpdateAgentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListModelsHandler := connect.NewUnaryHandler(
		AgentServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(agentServiceListModelsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceListAgentsProcedure:
			agentServiceListAgentsHandler.ServeHTTP(w, r)
		case AgentServiceCreateAgentProcedure:
			agentServiceCreateAgentHandler.ServeHTTP(w, r)
		case AgentServiceDeleteAgentProcedure:
			agentServiceDeleteAgentHandler.ServeHTTP(w, r)
		case AgentServiceUpdateAgentProcedure:
			agentServiceUpdateAgentHandler.ServeHTTP(w, r)
		case AgentServiceListModelsProcedure:
			agentServiceListModelsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AgentService.ListAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AgentService.CreateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AgentService.DeleteAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AgentService.UpdateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AgentService.ListModels is not implemented"))
}

// SkillServiceClient is a client for the aleph.v1.SkillService service.
type SkillServiceClient interface {
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error)
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
}

// NewSkillServiceClient constructs a client for the aleph.v1.SkillService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSkillServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SkillServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &skillServiceClient{
		listSkills: connect.NewClient[v1.ListSkillsRequest, v1.ListSkillsResponse](
			httpClient,
			baseURL+SkillServiceListSkillsProcedure,
			connect.WithSchema(skillServiceListSkillsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createSkill: connect.NewClient[v1.CreateSkillRequest, v1.CreateSkillResponse](
			httpClient,
			baseURL+SkillServiceCreateSkillProcedure,
			connect.WithSchema(skillServiceCreateSkillMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateSkill: connect.NewClient[v1.UpdateSkillRequest, v1.UpdateSkillResponse](
			httpClient,
			baseURL+SkillServiceUpdateSkillProcedure,
			connect.WithSchema(skillServiceUpdateSkillMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteSkill: connect.NewClient[v1.DeleteSkillRequest, v1.DeleteSkillResponse](
			httpClient,
			baseURL+SkillServiceDeleteSkillProcedure,
			connect.WithSchema(skillServiceDeleteSkillMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// skillServiceClient implements SkillServiceClient.
type skillServiceClient struct {
	listSkills  *connect.Client[v1.ListSkillsRequest, v1.ListSkillsResponse]
	createSkill *connect.Client[v1.CreateSkillRequest, v1.CreateSkillResponse]
	updateSkill *connect.Client[v1.UpdateSkillRequest, v1.UpdateSkillResponse]
	deleteSkill *connect.Client[v1.DeleteSkillRequest, v1.DeleteSkillResponse]
}

// ListSkills calls aleph.v1.SkillService.ListSkills.
func (c *skillServiceClient) ListSkills(ctx context.Context, req *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return c.listSkills.CallUnary(ctx, req)
}

// CreateSkill calls aleph.v1.SkillService.CreateSkill.
func (c *skillServiceClient) CreateSkill(ctx context.Context, req *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error) {
	return c.createSkill.CallUnary(ctx, req)
}

// UpdateSkill calls aleph.v1.SkillService.UpdateSkill.
func (c *skillServiceClient) UpdateSkill(ctx context.Context, req *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return c.updateSkill.CallUnary(ctx, req)
}

// DeleteSkill calls aleph.v1.SkillService.DeleteSkill.
func (c *skillServiceClient) DeleteSkill(ctx context.Context, req *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return c.deleteSkill.CallUnary(ctx, req)
}

// SkillServiceHandler is an implementation of the aleph.v1.SkillService service.
type SkillServiceHandler interface {
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error)
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
}

// NewSkillServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSkillServiceHandler(svc SkillServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	skillServiceListSkillsHandler := connect.NewUnaryHandler(
		SkillServiceListSkillsProcedure,
		svc.ListSkills,
		connect.WithSchema(skillServiceListSkillsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	skillServiceCreateSkillHandler := connect.NewUnaryHandler(
		SkillServiceCreateSkillProcedure,
		svc.CreateSkill,
		connect.WithSchema(skillServiceCreateSkillMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	skillServiceUpdateSkillHandler := connect.NewUnaryHandler(
		SkillServiceUpdateSkillProcedure,
		svc.UpdateSkill,
		connect.WithSchema(skillServiceUpdateSkillMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	skillServiceDeleteSkillHandler := connect.NewUnaryHandler(
		SkillServiceDeleteSkillProcedure,
		svc.DeleteSkill,
		connect.WithSchema(skillServiceDeleteSkillMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.SkillService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SkillServiceListSkillsProcedure:
			skillServiceListSkillsHandler.ServeHTTP(w, r)
		case SkillServiceCreateSkillProcedure:
			skillServiceCreateSkillHandler.ServeHTTP(w, r)
		case SkillServiceUpdateSkillProcedure:
			skillServiceUpdateSkillHandler.ServeHTTP(w, r)
		case SkillServiceDeleteSkillProcedure:
			skillServiceDeleteSkillHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSkillServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSkillServiceHandler struct{}

func (UnimplementedSkillServiceHandler) ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.SkillService.ListSkills is not implemented"))
}

func (UnimplementedSkillServiceHandler) CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.SkillService.CreateSkill is not implemented"))
}

func (UnimplementedSkillServiceHandler) UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.SkillService.UpdateSkill is not implemented"))
}

func (UnimplementedSkillServiceHandler) DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.SkillService.DeleteSkill is not implemented"))
}

// ToolServiceClient is a client for the aleph.v1.ToolService service.
type ToolServiceClient interface {
	ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error)
	CreateTool(context.Context, *connect.Request[v1.CreateToolRequest]) (*connect.Response[v1.CreateToolResponse], error)
	UpdateTool(context.Context, *connect.Request[v1.UpdateToolRequest]) (*connect.Response[v1.UpdateToolResponse], error)
	DeleteTool(context.Context, *connect.Request[v1.DeleteToolRequest]) (*connect.Response[v1.DeleteToolResponse], error)
}

// NewToolServiceClient constructs a client for the aleph.v1.ToolService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewToolServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ToolServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &toolServiceClient{
		listTools: connect.NewClient[v1.ListToolsRequest, v1.ListToolsResponse](
			httpClient,
			baseURL+ToolServiceListToolsProcedure,
			connect.WithSchema(toolServiceListToolsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createTool: connect.NewClient[v1.CreateToolRequest, v1.CreateToolResponse](
			httpClient,
			baseURL+ToolServiceCreateToolProcedure,
			connect.WithSchema(toolServiceCreateToolMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateTool: connect.NewClient[v1.UpdateToolRequest, v1.UpdateToolResponse](
			httpClient,
			baseURL+ToolServiceUpdateToolProcedure,
			connect.WithSchema(toolServiceUpdateToolMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteTool: connect.NewClient[v1.DeleteToolRequest, v1.DeleteToolResponse](
			httpClient,
			baseURL+ToolServiceDeleteToolProcedure,
			connect.WithSchema(toolServiceDeleteToolMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// toolServiceClient implements ToolServiceClient.
type toolServiceClient struct {
	listTools  *connect.Client[v1.ListToolsRequest, v1.ListToolsResponse]
	createTool *connect.Client[v1.CreateToolRequest, v1.CreateToolResponse]
	updateTool *connect.Client[v1.UpdateToolRequest, v1.UpdateToolResponse]
	deleteTool *connect.Client[v1.DeleteToolRequest, v1.DeleteToolResponse]
}

// ListTools calls aleph.v1.ToolService.ListTools.
func (c *toolServiceClient) ListTools(ctx context.Context, req *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error) {
	return c.listTools.CallUnary(ctx, req)
}

// CreateTool calls aleph.v1.ToolService.CreateTool.
func (c *toolServiceClient) CreateTool(ctx context.Context, req *connect.Request[v1.CreateToolRequest]) (*connect.Response[v1.CreateToolResponse], error) {
	return c.createTool.CallUnary(ctx, req)
}

// UpdateTool calls aleph.v1.ToolService.UpdateTool.
func (c *toolServiceClient) UpdateTool(ctx context.Context, req *connect.Request[v1.UpdateToolRequest]) (*connect.Response[v1.UpdateToolResponse], error) {
	return c.updateTool.CallUnary(ctx, req)
}

// DeleteTool calls aleph.v1.ToolService.DeleteTool.
func (c *toolServiceClient) DeleteTool(ctx context.Context, req *connect.Request[v1.DeleteToolRequest]) (*connect.Response[v1.DeleteToolResponse], error) {
	return c.deleteTool.CallUnary(ctx, req)
}

// ToolServiceHandler is an implementation of the aleph.v1.ToolService service.
type ToolServiceHandler interface {
	ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error)
	CreateTool(context.Context, *connect.Request[v1.CreateToolRequest]) (*connect.Response[v1.CreateToolResponse], error)
	UpdateTool(context.Context, *connect.Request[v1.UpdateToolRequest]) (*connect.Response[v1.UpdateToolResponse], error)
	DeleteTool(context.Context, *connect.Request[v1.DeleteToolRequest]) (*connect.Response[v1.DeleteToolResponse], error)
}

// NewToolServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewToolServiceHandler(svc ToolServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	toolServiceListToolsHandler := connect.NewUnaryHandler(
		ToolServiceListToolsProcedure,
		svc.ListTools,
		connect.WithSchema(toolServiceListToolsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toolServiceCreateToolHandler := connect.NewUnaryHandler(
		ToolServiceCreateToolProcedure,
		svc.CreateTool,
		connect.WithSchema(toolServiceCreateToolMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toolServiceUpdateToolHandler := connect.NewUnaryHandler(
		ToolServiceUpdateToolProcedure,
		svc.UpdateTool,
		connect.WithSchema(toolServiceUpdateToolMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	toolServiceDeleteToolHandler := connect.NewUnaryHandler(
		ToolServiceDeleteToolProcedure,
		svc.DeleteTool,
		connect.WithSchema(toolServiceDeleteToolMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.ToolService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ToolServiceListToolsProcedure:
			toolServiceListToolsHandler.ServeHTTP(w, r)
		case ToolServiceCreateToolProcedure:
			toolServiceCreateToolHandler.ServeHTTP(w, r)
		case ToolServiceUpdateToolProcedure:
			toolServiceUpdateToolHandler.ServeHTTP(w, r)
		case ToolServiceDeleteToolProcedure:
			toolServiceDeleteToolHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedToolServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedToolServiceHandler struct{}

func (UnimplementedToolServiceHandler) ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ToolService.ListTools is not implemented"))
}

func (UnimplementedToolServiceHandler) CreateTool(context.Context, *connect.Request[v1.CreateToolRequest]) (*connect.Response[v1.CreateToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ToolService.CreateTool is not implemented"))
}

func (UnimplementedToolServiceHandler) UpdateTool(context.Context, *connect.Request[v1.UpdateToolRequest]) (*connect.Response[v1.UpdateToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ToolService.UpdateTool is not implemented"))
}

func (UnimplementedToolServiceHandler) DeleteTool(context.Context, *connect.Request[v1.DeleteToolRequest]) (*connect.Response[v1.DeleteToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.ToolService.DeleteTool is not implemented"))
}

// LibraryServiceClient is a client for the aleph.v1.LibraryService service.
type LibraryServiceClient interface {
	ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error)
	GetAssetContent(context.Context, *connect.Request[v1.GetAssetContentRequest]) (*connect.Response[v1.GetAssetContentResponse], error)
	DeleteAsset(context.Context, *connect.Request[v1.DeleteAssetRequest]) (*connect.Response[v1.DeleteAssetResponse], error)
	GeneratePdf(context.Context, *connect.Request[v1.GeneratePdfRequest]) (*connect.Response[v1.GeneratePdfResponse], error)
	UploadAsset(context.Context, *connect.Request[v1.UploadAssetRequest]) (*connect.Response[v1.UploadAssetResponse], error)
}

// NewLibraryServiceClient constructs a client for the aleph.v1.LibraryService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLibraryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LibraryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &libraryServiceClient{
		listAssets: connect.NewClient[v1.ListAssetsRequest, v1.ListAssetsResponse](
			httpClient,
			baseURL+LibraryServiceListAssetsProcedure,
			connect.WithSchema(libraryServiceListAssetsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAssetContent: connect.NewClient[v1.GetAssetContentRequest, v1.GetAssetContentResponse](
			httpClient,
			baseURL+LibraryServiceGetAssetContentProcedure,
			connect.WithSchema(libraryServiceGetAssetContentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteAsset: connect.NewClient[v1.DeleteAssetRequest, v1.DeleteAssetResponse](
			httpClient,
			baseURL+LibraryServiceDeleteAssetProcedure,
			connect.WithSchema(libraryServiceDeleteAssetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		generatePdf: connect.NewClient[v1.GeneratePdfRequest, v1.GeneratePdfResponse](
			httpClient,
			baseURL+LibraryServiceGeneratePdfProcedure,
			connect.WithSchema(libraryServiceGeneratePdfMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		uploadAsset: connect.NewClient[v1.UploadAssetRequest, v1.UploadAssetResponse](
			httpClient,
			baseURL+LibraryServiceUploadAssetProcedure,
			connect.WithSchema(libraryServiceUploadAssetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// libraryServiceClient implements LibraryServiceClient.
type libraryServiceClient struct {
	listAssets      *connect.Client[v1.ListAssetsRequest, v1.ListAssetsResponse]
	getAssetContent *connect.Client[v1.GetAssetContentRequest, v1.GetAssetContentResponse]
	deleteAsset     *connect.Client[v1.DeleteAssetRequest, v1.DeleteAssetResponse]
	generatePdf     *connect.Client[v1.GeneratePdfRequest, v1.GeneratePdfResponse]
	uploadAsset     *connect.Client[v1.UploadAssetRequest, v1.UploadAssetResponse]
}

// ListAssets calls aleph.v1.LibraryService.ListAssets.
func (c *libraryServiceClient) ListAssets(ctx context.Context, req *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error) {
	return c.listAssets.CallUnary(ctx, req)
}

// GetAssetContent calls aleph.v1.LibraryService.GetAssetContent.
func (c *libraryServiceClient) GetAssetContent(ctx context.Context, req *connect.Request[v1.GetAssetContentRequest]) (*connect.Response[v1.GetAssetContentResponse], error) {
	return c.getAssetContent.CallUnary(ctx, req)
}

// DeleteAsset calls aleph.v1.LibraryService.DeleteAsset.
func (c *libraryServiceClient) DeleteAsset(ctx context.Context, req *connect.Request[v1.DeleteAssetRequest]) (*connect.Response[v1.DeleteAssetResponse], error) {
	return c.deleteAsset.CallUnary(ctx, req)
}

// GeneratePdf calls aleph.v1.LibraryService.GeneratePdf.
func (c *libraryServiceClient) GeneratePdf(ctx context.Context, req *connect.Request[v1.GeneratePdfRequest]) (*connect.Response[v1.GeneratePdfResponse], error) {
	return c.generatePdf.CallUnary(ctx, req)
}

// UploadAsset calls aleph.v1.LibraryService.UploadAsset.
func (c *libraryServiceClient) UploadAsset(ctx context.Context, req *connect.Request[v1.UploadAssetRequest]) (*connect.Response[v1.UploadAssetResponse], error) {
	return c.uploadAsset.CallUnary(ctx, req)
}

// LibraryServiceHandler is an implementation of the aleph.v1.LibraryService service.
type LibraryServiceHandler interface {
	ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error)
	GetAssetContent(context.Context, *connect.Request[v1.GetAssetContentRequest]) (*connect.Response[v1.GetAssetContentResponse], error)
	DeleteAsset(context.Context, *connect.Request[v1.DeleteAssetRequest]) (*connect.Response[v1.DeleteAssetResponse], error)
	GeneratePdf(context.Context, *connect.Request[v1.GeneratePdfRequest]) (*connect.Response[v1.GeneratePdfResponse], error)
	UploadAsset(context.Context, *connect.Request[v1.UploadAssetRequest]) (*connect.Response[v1.UploadAssetResponse], error)
}

// NewLibraryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLibraryServiceHandler(svc LibraryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	libraryServiceListAssetsHandler := connect.NewUnaryHandler(
		LibraryServiceListAssetsProcedure,
		svc.ListAssets,
		connect.WithSchema(libraryServiceListAssetsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	libraryServiceGetAssetContentHandler := connect.NewUnaryHandler(
		LibraryServiceGetAssetContentProcedure,
		svc.GetAssetContent,
		connect.WithSchema(libraryServiceGetAssetContentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	libraryServiceDeleteAssetHandler := connect.NewUnaryHandler(
		LibraryServiceDeleteAssetProcedure,
		svc.DeleteAsset,
		connect.WithSchema(libraryServiceDeleteAssetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	libraryServiceGeneratePdfHandler := connect.NewUnaryHandler(
		LibraryServiceGeneratePdfProcedure,
		svc.GeneratePdf,
		connect.WithSchema(libraryServiceGeneratePdfMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	libraryServiceUploadAssetHandler := connect.NewUnaryHandler(
		LibraryServiceUploadAssetProcedure,
		svc.UploadAsset,
		connect.WithSchema(libraryServiceUploadAssetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.LibraryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LibraryServiceListAssetsProcedure:
			libraryServiceListAssetsHandler.ServeHTTP(w, r)
		case LibraryServiceGetAssetContentProcedure:
			libraryServiceGetAssetContentHandler.ServeHTTP(w, r)
		case LibraryServiceDeleteAssetProcedure:
			libraryServiceDeleteAssetHandler.ServeHTTP(w, r)
		case LibraryServiceGeneratePdfProcedure:
			libraryServiceGeneratePdfHandler.ServeHTTP(w, r)
		case LibraryServiceUploadAssetProcedure:
			libraryServiceUploadAssetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLibraryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLibraryServiceHandler struct{}

func (UnimplementedLibraryServiceHandler) ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.LibraryService.ListAssets is not implemented"))
}

func (UnimplementedLibraryServiceHandler) GetAssetContent(context.Context, *connect.Request[v1.GetAssetContentRequest]) (*connect.Response[v1.GetAssetContentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.LibraryService.GetAssetContent is not implemented"))
}

func (UnimplementedLibraryServiceHandler) DeleteAsset(context.Context, *connect.Request[v1.DeleteAssetRequest]) (*connect.Response[v1.DeleteAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.LibraryService.DeleteAsset is not implemented"))
}

func (UnimplementedLibraryServiceHandler) GeneratePdf(context.Context, *connect.Request[v1.GeneratePdfRequest]) (*connect.Response[v1.GeneratePdfResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.LibraryService.GeneratePdf is not implemented"))
}

func (UnimplementedLibraryServiceHandler) UploadAsset(context.Context, *connect.Request[v1.UploadAssetRequest]) (*connect.Response[v1.UploadAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.LibraryService.UploadAsset is not implemented"))
}

// AuthServiceClient is a client for the aleph.v1.AuthService service.
type AuthServiceClient interface {
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	DeleteApiKey(context.Context, *connect.Request[v1.DeleteApiKeyRequest]) (*connect.Response[v1.DeleteApiKeyResponse], error)
}

// NewAuthServiceClient constructs a client for the aleph.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		listApiKeys: connect.NewClient[v1.ListApiKeysRequest, v1.ListApiKeysResponse](
			httpClient,
			baseURL+AuthServiceListApiKeysProcedure,
			connect.WithSchema(authServiceListApiKeysMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createApiKey: connect.NewClient[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse](
			httpClient,
			baseURL+AuthServiceCreateApiKeyProcedure,
			connect.WithSchema(authServiceCreateApiKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteApiKey: connect.NewClient[v1.DeleteApiKeyRequest, v1.DeleteApiKeyResponse](
			httpClient,
			baseURL+AuthServiceDeleteApiKeyProcedure,
			connect.WithSchema(authServiceDeleteApiKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	listApiKeys  *connect.Client[v1.ListApiKeysRequest, v1.ListApiKeysResponse]
	createApiKey *connect.Client[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse]
	deleteApiKey *connect.Client[v1.DeleteApiKeyRequest, v1.DeleteApiKeyResponse]
}

// ListApiKeys calls aleph.v1.AuthService.ListApiKeys.
func (c *authServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// CreateApiKey calls aleph.v1.AuthService.CreateApiKey.
func (c *authServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// DeleteApiKey calls aleph.v1.AuthService.DeleteApiKey.
func (c *authServiceClient) DeleteApiKey(ctx context.Context, req *connect.Request[v1.DeleteApiKeyRequest]) (*connect.Response[v1.DeleteApiKeyResponse], error) {
	return c.deleteApiKey.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the aleph.v1.AuthService service.
type AuthServiceHandler interface {
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	DeleteApiKey(context.Context, *connect.Request[v1.DeleteApiKeyRequest]) (*connect.Response[v1.DeleteApiKeyResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceListApiKeysHandler := connect.NewUnaryHandler(
		AuthServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(authServiceListApiKeysMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		AuthServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(authServiceCreateApiKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeleteApiKeyHandler := connect.NewUnaryHandler(
		AuthServiceDeleteApiKeyProcedure,
		svc.DeleteApiKey,
		connect.WithSchema(authServiceDeleteApiKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceListApiKeysProcedure:
			authServiceListApiKeysHandler.ServeHTTP(w, r)
		case AuthServiceCreateApiKeyProcedure:
			authServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case AuthServiceDeleteApiKeyProcedure:
			authServiceDeleteApiKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AuthService.ListApiKeys is not implemented"))
}

func (UnimplementedAuthServiceHandler) CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AuthService.CreateApiKey is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeleteApiKey(context.Context, *connect.Request[v1.DeleteApiKeyRequest]) (*connect.Response[v1.DeleteApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.v1.AuthService.DeleteApiKey is not implemented"))
}
