// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aleph/v1/registry.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RegistryServiceName is the fully-qualified name of the RegistryService service.
	RegistryServiceName = "aleph.registry.v1.RegistryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RegistryServiceRegisterComponentProcedure is the fully-qualified name of the RegistryService's
	// RegisterComponent RPC.
	RegistryServiceRegisterComponentProcedure = "/aleph.registry.v1.RegistryService/RegisterComponent"
	// RegistryServiceGetComponentProcedure is the fully-qualified name of the RegistryService's
	// GetComponent RPC.
	RegistryServiceGetComponentProcedure = "/aleph.registry.v1.RegistryService/GetComponent"
	// RegistryServiceListComponentsProcedure is the fully-qualified name of the RegistryService's
	// ListComponents RPC.
	RegistryServiceListComponentsProcedure = "/aleph.registry.v1.RegistryService/ListComponents"
	// RegistryServiceUpdateComponentStatusProcedure is the fully-qualified name of the
	// RegistryService's UpdateComponentStatus RPC.
	RegistryServiceUpdateComponentStatusProcedure = "/aleph.registry.v1.RegistryService/UpdateComponentStatus"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	registryServiceServiceDescriptor                     = v1.File_aleph_v1_registry_proto.Services().ByName("RegistryService")
	registryServiceRegisterComponentMethodDescriptor     = registryServiceServiceDescriptor.Methods().ByName("RegisterComponent")
	registryServiceGetComponentMethodDescriptor          = registryServiceServiceDescriptor.Methods().ByName("GetComponent")
	registryServiceListComponentsMethodDescriptor        = registryServiceServiceDescriptor.Methods().ByName("ListComponents")
	registryServiceUpdateComponentStatusMethodDescriptor = registryServiceServiceDescriptor.Methods().ByName("UpdateComponentStatus")
)

// RegistryServiceClient is a client for the aleph.registry.v1.RegistryService service.
type RegistryServiceClient interface {
	RegisterComponent(context.Context, *connect.Request[v1.RegisterComponentRequest]) (*connect.Response[v1.RegisterComponentResponse], error)
	GetComponent(context.Context, *connect.Request[v1.GetComponentRequest]) (*connect.Response[v1.GetComponentResponse], error)
	ListComponents(context.Context, *connect.Request[v1.ListComponentsRequest]) (*connect.Response[v1.ListComponentsResponse], error)
	UpdateComponentStatus(context.Context, *connect.Request[v1.UpdateComponentStatusRequest]) (*connect.Response[v1.UpdateComponentStatusResponse], error)
}

// NewRegistryServiceClient constructs a client for the aleph.registry.v1.RegistryService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRegistryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RegistryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &registryServiceClient{
		registerComponent: connect.NewClient[v1.RegisterComponentRequest, v1.RegisterComponentResponse](
			httpClient,
			baseURL+RegistryServiceRegisterComponentProcedure,
			connect.WithSchema(registryServiceRegisterComponentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getComponent: connect.NewClient[v1.GetComponentRequest, v1.GetComponentResponse](
			httpClient,
			baseURL+RegistryServiceGetComponentProcedure,
			connect.WithSchema(registryServiceGetComponentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listComponents: connect.NewClient[v1.ListComponentsRequest, v1.ListComponentsResponse](
			httpClient,
			baseURL+RegistryServiceListComponentsProcedure,
			connect.WithSchema(registryServiceListComponentsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateComponentStatus: connect.NewClient[v1.UpdateComponentStatusRequest, v1.UpdateComponentStatusResponse](
			httpClient,
			baseURL+RegistryServiceUpdateComponentStatusProcedure,
			connect.WithSchema(registryServiceUpdateComponentStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// registryServiceClient implements RegistryServiceClient.
type registryServiceClient struct {
	registerComponent     *connect.Client[v1.RegisterComponentRequest, v1.RegisterComponentResponse]
	getComponent          *connect.Client[v1.GetComponentRequest, v1.GetComponentResponse]
	listComponents        *connect.Client[v1.ListComponentsRequest, v1.ListComponentsResponse]
	updateComponentStatus *connect.Client[v1.UpdateComponentStatusRequest, v1.UpdateComponentStatusResponse]
}

// RegisterComponent calls aleph.registry.v1.RegistryService.RegisterComponent.
func (c *registryServiceClient) RegisterComponent(ctx context.Context, req *connect.Request[v1.RegisterComponentRequest]) (*connect.Response[v1.RegisterComponentResponse], error) {
	return c.registerComponent.CallUnary(ctx, req)
}

// GetComponent calls aleph.registry.v1.RegistryService.GetComponent.
func (c *registryServiceClient) GetComponent(ctx context.Context, req *connect.Request[v1.GetComponentRequest]) (*connect.Response[v1.GetComponentResponse], error) {
	return c.getComponent.CallUnary(ctx, req)
}

// ListComponents calls aleph.registry.v1.RegistryService.ListComponents.
func (c *registryServiceClient) ListComponents(ctx context.Context, req *connect.Request[v1.ListComponentsRequest]) (*connect.Response[v1.ListComponentsResponse], error) {
	return c.listComponents.CallUnary(ctx, req)
}

// UpdateComponentStatus calls aleph.registry.v1.RegistryService.UpdateComponentStatus.
func (c *registryServiceClient) UpdateComponentStatus(ctx context.Context, req *connect.Request[v1.UpdateComponentStatusRequest]) (*connect.Response[v1.UpdateComponentStatusResponse], error) {
	return c.updateComponentStatus.CallUnary(ctx, req)
}

// RegistryServiceHandler is an implementation of the aleph.registry.v1.RegistryService service.
type RegistryServiceHandler interface {
	RegisterComponent(context.Context, *connect.Request[v1.RegisterComponentRequest]) (*connect.Response[v1.RegisterComponentResponse], error)
	GetComponent(context.Context, *connect.Request[v1.GetComponentRequest]) (*connect.Response[v1.GetComponentResponse], error)
	ListComponents(context.Context, *connect.Request[v1.ListComponentsRequest]) (*connect.Response[v1.ListComponentsResponse], error)
	UpdateComponentStatus(context.Context, *connect.Request[v1.UpdateComponentStatusRequest]) (*connect.Response[v1.UpdateComponentStatusResponse], error)
}

// NewRegistryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRegistryServiceHandler(svc RegistryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	registryServiceRegisterComponentHandler := connect.NewUnaryHandler(
		RegistryServiceRegisterComponentProcedure,
		svc.RegisterComponent,
		connect.WithSchema(registryServiceRegisterComponentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceGetComponentHandler := connect.NewUnaryHandler(
		RegistryServiceGetComponentProcedure,
		svc.GetComponent,
		connect.WithSchema(registryServiceGetComponentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceListComponentsHandler := connect.NewUnaryHandler(
		RegistryServiceListComponentsProcedure,
		svc.ListComponents,
		connect.WithSchema(registryServiceListComponentsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceUpdateComponentStatusHandler := connect.NewUnaryHandler(
		RegistryServiceUpdateComponentStatusProcedure,
		svc.UpdateComponentStatus,
		connect.WithSchema(registryServiceUpdateComponentStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.registry.v1.RegistryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RegistryServiceRegisterComponentProcedure:
			registryServiceRegisterComponentHandler.ServeHTTP(w, r)
		case RegistryServiceGetComponentProcedure:
			registryServiceGetComponentHandler.ServeHTTP(w, r)
		case RegistryServiceListComponentsProcedure:
			registryServiceListComponentsHandler.ServeHTTP(w, r)
		case RegistryServiceUpdateComponentStatusProcedure:
			registryServiceUpdateComponentStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRegistryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRegistryServiceHandler struct{}

func (UnimplementedRegistryServiceHandler) RegisterComponent(context.Context, *connect.Request[v1.RegisterComponentRequest]) (*connect.Response[v1.RegisterComponentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.registry.v1.RegistryService.RegisterComponent is not implemented"))
}

func (UnimplementedRegistryServiceHandler) GetComponent(context.Context, *connect.Request[v1.GetComponentRequest]) (*connect.Response[v1.GetComponentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.registry.v1.RegistryService.GetComponent is not implemented"))
}

func (UnimplementedRegistryServiceHandler) ListComponents(context.Context, *connect.Request[v1.ListComponentsRequest]) (*connect.Response[v1.ListComponentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.registry.v1.RegistryService.ListComponents is not implemented"))
}

func (UnimplementedRegistryServiceHandler) UpdateComponentStatus(context.Context, *connect.Request[v1.UpdateComponentStatusRequest]) (*connect.Response[v1.UpdateComponentStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.registry.v1.RegistryService.UpdateComponentStatus is not implemented"))
}
