// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aleph/v1/sandbox.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ff3300/aleph-v2/internal/api/proto/aleph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SandboxServiceName is the fully-qualified name of the SandboxService service.
	SandboxServiceName = "aleph.tool.v1.SandboxService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SandboxServiceExecuteToolProcedure is the fully-qualified name of the SandboxService's
	// ExecuteTool RPC.
	SandboxServiceExecuteToolProcedure = "/aleph.tool.v1.SandboxService/ExecuteTool"
	// SandboxServiceRunSkillProcedure is the fully-qualified name of the SandboxService's RunSkill RPC.
	SandboxServiceRunSkillProcedure = "/aleph.tool.v1.SandboxService/RunSkill"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	sandboxServiceServiceDescriptor           = v1.File_aleph_v1_sandbox_proto.Services().ByName("SandboxService")
	sandboxServiceExecuteToolMethodDescriptor = sandboxServiceServiceDescriptor.Methods().ByName("ExecuteTool")
	sandboxServiceRunSkillMethodDescriptor    = sandboxServiceServiceDescriptor.Methods().ByName("RunSkill")
)

// SandboxServiceClient is a client for the aleph.tool.v1.SandboxService service.
type SandboxServiceClient interface {
	ExecuteTool(context.Context, *connect.Request[v1.ExecuteToolRequest]) (*connect.Response[v1.ExecuteToolResponse], error)
	RunSkill(context.Context, *connect.Request[v1.RunSkillRequest]) (*connect.Response[v1.RunSkillResponse], error)
}

// NewSandboxServiceClient constructs a client for the aleph.tool.v1.SandboxService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSandboxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SandboxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &sandboxServiceClient{
		executeTool: connect.NewClient[v1.ExecuteToolRequest, v1.ExecuteToolResponse](
			httpClient,
			baseURL+SandboxServiceExecuteToolProcedure,
			connect.WithSchema(sandboxServiceExecuteToolMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		runSkill: connect.NewClient[v1.RunSkillRequest, v1.RunSkillResponse](
			httpClient,
			baseURL+SandboxServiceRunSkillProcedure,
			connect.WithSchema(sandboxServiceRunSkillMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// sandboxServiceClient implements SandboxServiceClient.
type sandboxServiceClient struct {
	executeTool *connect.Client[v1.ExecuteToolRequest, v1.ExecuteToolResponse]
	runSkill    *connect.Client[v1.RunSkillRequest, v1.RunSkillResponse]
}

// ExecuteTool calls aleph.tool.v1.SandboxService.ExecuteTool.
func (c *sandboxServiceClient) ExecuteTool(ctx context.Context, req *connect.Request[v1.ExecuteToolRequest]) (*connect.Response[v1.ExecuteToolResponse], error) {
	return c.executeTool.CallUnary(ctx, req)
}

// RunSkill calls aleph.tool.v1.SandboxService.RunSkill.
func (c *sandboxServiceClient) RunSkill(ctx context.Context, req *connect.Request[v1.RunSkillRequest]) (*connect.Response[v1.RunSkillResponse], error) {
	return c.runSkill.CallUnary(ctx, req)
}

// SandboxServiceHandler is an implementation of the aleph.tool.v1.SandboxService service.
type SandboxServiceHandler interface {
	ExecuteTool(context.Context, *connect.Request[v1.ExecuteToolRequest]) (*connect.Response[v1.ExecuteToolResponse], error)
	RunSkill(context.Context, *connect.Request[v1.RunSkillRequest]) (*connect.Response[v1.RunSkillResponse], error)
}

// NewSandboxServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSandboxServiceHandler(svc SandboxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sandboxServiceExecuteToolHandler := connect.NewUnaryHandler(
		SandboxServiceExecuteToolProcedure,
		svc.ExecuteTool,
		connect.WithSchema(sandboxServiceExecuteToolMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceRunSkillHandler := connect.NewUnaryHandler(
		SandboxServiceRunSkillProcedure,
		svc.RunSkill,
		connect.WithSchema(sandboxServiceRunSkillMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/aleph.tool.v1.SandboxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SandboxServiceExecuteToolProcedure:
			sandboxServiceExecuteToolHandler.ServeHTTP(w, r)
		case SandboxServiceRunSkillProcedure:
			sandboxServiceRunSkillHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSandboxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSandboxServiceHandler struct{}

func (UnimplementedSandboxServiceHandler) ExecuteTool(context.Context, *connect.Request[v1.ExecuteToolRequest]) (*connect.Response[v1.ExecuteToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.tool.v1.SandboxService.ExecuteTool is not implemented"))
}

func (UnimplementedSandboxServiceHandler) RunSkill(context.Context, *connect.Request[v1.RunSkillRequest]) (*connect.Response[v1.RunSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aleph.tool.v1.SandboxService.RunSkill is not implemented"))
}
