// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nlp.proto

package nlp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntityId        string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	IsCorrect       bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	CorrectionValue string                 `protobuf:"bytes,3,opt,name=correction_value,json=correctionValue,proto3" json:"correction_value,omitempty"` // "Questo importo è errato, dovrebbe essere Y"
	FeedbackType    string                 `protobuf:"bytes,4,opt,name=feedback_type,json=feedbackType,proto3" json:"feedback_type,omitempty"`          // "prediction", "action_proposal"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FeedbackRequest) Reset() {
	*x = FeedbackRequest{}
	mi := &file_nlp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackRequest) ProtoMessage() {}

func (x *FeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackRequest.ProtoReflect.Descriptor instead.
func (*FeedbackRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{0}
}

func (x *FeedbackRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *FeedbackRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *FeedbackRequest) GetCorrectionValue() string {
	if x != nil {
		return x.CorrectionValue
	}
	return ""
}

func (x *FeedbackRequest) GetFeedbackType() string {
	if x != nil {
		return x.FeedbackType
	}
	return ""
}

type FeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackResponse) Reset() {
	*x = FeedbackResponse{}
	mi := &file_nlp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResponse) ProtoMessage() {}

func (x *FeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResponse.ProtoReflect.Descriptor instead.
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *FeedbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AnalyzeSentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSentimentRequest) Reset() {
	*x = AnalyzeSentimentRequest{}
	mi := &file_nlp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSentimentRequest) ProtoMessage() {}

func (x *AnalyzeSentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSentimentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSentimentRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeSentimentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzeSentimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSentimentResponse) Reset() {
	*x = AnalyzeSentimentResponse{}
	mi := &file_nlp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSentimentResponse) ProtoMessage() {}

func (x *AnalyzeSentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSentimentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSentimentResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeSentimentResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnalyzeSentimentResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PredictiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	OntologyQuery string                 `protobuf:"bytes,2,opt,name=ontology_query,json=ontologyQuery,proto3" json:"ontology_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictiveRequest) Reset() {
	*x = PredictiveRequest{}
	mi := &file_nlp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictiveRequest) ProtoMessage() {}

func (x *PredictiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictiveRequest.ProtoReflect.Descriptor instead.
func (*PredictiveRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{4}
}

func (x *PredictiveRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *PredictiveRequest) GetOntologyQuery() string {
	if x != nil {
		return x.OntologyQuery
	}
	return ""
}

type PredictiveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityId       string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Probability    float32                `protobuf:"fixed32,2,opt,name=probability,proto3" json:"probability,omitempty"`
	PredictedState string                 `protobuf:"bytes,3,opt,name=predicted_state,json=predictedState,proto3" json:"predicted_state,omitempty"`
	Explanation    string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PredictiveResponse) Reset() {
	*x = PredictiveResponse{}
	mi := &file_nlp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictiveResponse) ProtoMessage() {}

func (x *PredictiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictiveResponse.ProtoReflect.Descriptor instead.
func (*PredictiveResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{5}
}

func (x *PredictiveResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PredictiveResponse) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *PredictiveResponse) GetPredictedState() string {
	if x != nil {
		return x.PredictedState
	}
	return ""
}

func (x *PredictiveResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_nlp_proto protoreflect.FileDescriptor

const file_nlp_proto_rawDesc = "" +
	"\n" +
	"\tnlp.proto\x12\faleph.nlp.v1\"\x9d\x01\n" +
	"\x0fFeedbackRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x12)\n" +
	"\x10correction_value\x18\x03 \x01(\tR\x0fcorrectionValue\x12#\n" +
	"\rfeedback_type\x18\x04 \x01(\tR\ffeedbackType\",\n" +
	"\x10FeedbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x17AnalyzeSentimentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"F\n" +
	"\x18AnalyzeSentimentResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"Y\n" +
	"\x11PredictiveRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12%\n" +
	"\x0eontology_query\x18\x02 \x01(\tR\rontologyQuery\"\x9e\x01\n" +
	"\x12PredictiveResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12 \n" +
	"\vprobability\x18\x02 \x01(\x02R\vprobability\x12'\n" +
	"\x0fpredicted_state\x18\x03 \x01(\tR\x0epredictedState\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation2\x9a\x02\n" +
	"\n" +
	"NLPService\x12a\n" +
	"\x10AnalyzeSentiment\x12%.aleph.nlp.v1.AnalyzeSentimentRequest\x1a&.aleph.nlp.v1.AnalyzeSentimentResponse\x12X\n" +
	"\x11StreamPredictions\x12\x1f.aleph.nlp.v1.PredictiveRequest\x1a .aleph.nlp.v1.PredictiveResponse0\x01\x12O\n" +
	"\x0eRecordFeedback\x12\x1d.aleph.nlp.v1.FeedbackRequest\x1a\x1e.aleph.nlp.v1.FeedbackResponseB3Z1github.com/ff3300/aleph-v2/internal/api/proto/nlpb\x06proto3"

var (
	file_nlp_proto_rawDescOnce sync.Once
	file_nlp_proto_rawDescData []byte
)

func file_nlp_proto_rawDescGZIP() []byte {
	file_nlp_proto_rawDescOnce.Do(func() {
		file_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nlp_proto_rawDesc), len(file_nlp_proto_rawDesc)))
	})
	return file_nlp_proto_rawDescData
}

var file_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nlp_proto_goTypes = []any{
	(*FeedbackRequest)(nil),          // 0: aleph.nlp.v1.FeedbackRequest
	(*FeedbackResponse)(nil),         // 1: aleph.nlp.v1.FeedbackResponse
	(*AnalyzeSentimentRequest)(nil),  // 2: aleph.nlp.v1.AnalyzeSentimentRequest
	(*AnalyzeSentimentResponse)(nil), // 3: aleph.nlp.v1.AnalyzeSentimentResponse
	(*PredictiveRequest)(nil),        // 4: aleph.nlp.v1.PredictiveRequest
	(*PredictiveResponse)(nil),       // 5: aleph.nlp.v1.PredictiveResponse
}
var file_nlp_proto_depIdxs = []int32{
	2, // 0: aleph.nlp.v1.NLPService.AnalyzeSentiment:input_type -> aleph.nlp.v1.AnalyzeSentimentRequest
	4, // 1: aleph.nlp.v1.NLPService.StreamPredictions:input_type -> aleph.nlp.v1.PredictiveRequest
	0, // 2: aleph.nlp.v1.NLPService.RecordFeedback:input_type -> aleph.nlp.v1.FeedbackRequest
	3, // 3: aleph.nlp.v1.NLPService.AnalyzeSentiment:output_type -> aleph.nlp.v1.AnalyzeSentimentResponse
	5, // 4: aleph.nlp.v1.NLPService.StreamPredictions:output_type -> aleph.nlp.v1.PredictiveResponse
	1, // 5: aleph.nlp.v1.NLPService.RecordFeedback:output_type -> aleph.nlp.v1.FeedbackResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nlp_proto_init() }
func file_nlp_proto_init() {
	if File_nlp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nlp_proto_rawDesc), len(file_nlp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nlp_proto_goTypes,
		DependencyIndexes: file_nlp_proto_depIdxs,
		MessageInfos:      file_nlp_proto_msgTypes,
	}.Build()
	File_nlp_proto = out.File
	file_nlp_proto_goTypes = nil
	file_nlp_proto_depIdxs = nil
}
