// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file aleph/nlp/v1/nlp.proto (package aleph.nlp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AnalyzeSentimentRequest, AnalyzeSentimentResponse, RecordFeedbackRequest, RecordFeedbackResponse, StreamPredictionsRequest, StreamPredictionsResponse } from "./nlp_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service aleph.nlp.v1.NLPService
 */
export const NLPService = {
  typeName: "aleph.nlp.v1.NLPService",
  methods: {
    /**
     * @generated from rpc aleph.nlp.v1.NLPService.AnalyzeSentiment
     */
    analyzeSentiment: {
      name: "AnalyzeSentiment",
      I: AnalyzeSentimentRequest,
      O: AnalyzeSentimentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Predictive Streams: Receive continuous knowledge updates
     *
     * @generated from rpc aleph.nlp.v1.NLPService.StreamPredictions
     */
    streamPredictions: {
      name: "StreamPredictions",
      I: StreamPredictionsRequest,
      O: StreamPredictionsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Active Learning: Close the loop with user validation
     *
     * @generated from rpc aleph.nlp.v1.NLPService.RecordFeedback
     */
    recordFeedback: {
      name: "RecordFeedback",
      I: RecordFeedbackRequest,
      O: RecordFeedbackResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

