// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file aleph/nlp/v1/nlp.proto (package aleph.nlp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message aleph.nlp.v1.RecordFeedbackRequest
 */
export class RecordFeedbackRequest extends Message<RecordFeedbackRequest> {
  /**
   * @generated from field: string entity_id = 1;
   */
  entityId = "";

  /**
   * @generated from field: bool is_correct = 2;
   */
  isCorrect = false;

  /**
   * "Questo importo è errato, dovrebbe essere Y"
   *
   * @generated from field: string correction_value = 3;
   */
  correctionValue = "";

  /**
   * "prediction", "action_proposal"
   *
   * @generated from field: string feedback_type = 4;
   */
  feedbackType = "";

  constructor(data?: PartialMessage<RecordFeedbackRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.RecordFeedbackRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_correct", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "correction_value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "feedback_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordFeedbackRequest {
    return new RecordFeedbackRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordFeedbackRequest {
    return new RecordFeedbackRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordFeedbackRequest {
    return new RecordFeedbackRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RecordFeedbackRequest | PlainMessage<RecordFeedbackRequest> | undefined, b: RecordFeedbackRequest | PlainMessage<RecordFeedbackRequest> | undefined): boolean {
    return proto3.util.equals(RecordFeedbackRequest, a, b);
  }
}

/**
 * @generated from message aleph.nlp.v1.RecordFeedbackResponse
 */
export class RecordFeedbackResponse extends Message<RecordFeedbackResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<RecordFeedbackResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.RecordFeedbackResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordFeedbackResponse {
    return new RecordFeedbackResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordFeedbackResponse {
    return new RecordFeedbackResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordFeedbackResponse {
    return new RecordFeedbackResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RecordFeedbackResponse | PlainMessage<RecordFeedbackResponse> | undefined, b: RecordFeedbackResponse | PlainMessage<RecordFeedbackResponse> | undefined): boolean {
    return proto3.util.equals(RecordFeedbackResponse, a, b);
  }
}

/**
 * @generated from message aleph.nlp.v1.AnalyzeSentimentRequest
 */
export class AnalyzeSentimentRequest extends Message<AnalyzeSentimentRequest> {
  /**
   * @generated from field: string text = 1;
   */
  text = "";

  constructor(data?: PartialMessage<AnalyzeSentimentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.AnalyzeSentimentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalyzeSentimentRequest {
    return new AnalyzeSentimentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalyzeSentimentRequest {
    return new AnalyzeSentimentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalyzeSentimentRequest {
    return new AnalyzeSentimentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AnalyzeSentimentRequest | PlainMessage<AnalyzeSentimentRequest> | undefined, b: AnalyzeSentimentRequest | PlainMessage<AnalyzeSentimentRequest> | undefined): boolean {
    return proto3.util.equals(AnalyzeSentimentRequest, a, b);
  }
}

/**
 * @generated from message aleph.nlp.v1.AnalyzeSentimentResponse
 */
export class AnalyzeSentimentResponse extends Message<AnalyzeSentimentResponse> {
  /**
   * @generated from field: float score = 1;
   */
  score = 0;

  /**
   * @generated from field: string label = 2;
   */
  label = "";

  constructor(data?: PartialMessage<AnalyzeSentimentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.AnalyzeSentimentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "score", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalyzeSentimentResponse {
    return new AnalyzeSentimentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalyzeSentimentResponse {
    return new AnalyzeSentimentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalyzeSentimentResponse {
    return new AnalyzeSentimentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AnalyzeSentimentResponse | PlainMessage<AnalyzeSentimentResponse> | undefined, b: AnalyzeSentimentResponse | PlainMessage<AnalyzeSentimentResponse> | undefined): boolean {
    return proto3.util.equals(AnalyzeSentimentResponse, a, b);
  }
}

/**
 * @generated from message aleph.nlp.v1.StreamPredictionsRequest
 */
export class StreamPredictionsRequest extends Message<StreamPredictionsRequest> {
  /**
   * @generated from field: string context_id = 1;
   */
  contextId = "";

  /**
   * @generated from field: string ontology_query = 2;
   */
  ontologyQuery = "";

  constructor(data?: PartialMessage<StreamPredictionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.StreamPredictionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "context_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ontology_query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamPredictionsRequest {
    return new StreamPredictionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamPredictionsRequest {
    return new StreamPredictionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamPredictionsRequest {
    return new StreamPredictionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamPredictionsRequest | PlainMessage<StreamPredictionsRequest> | undefined, b: StreamPredictionsRequest | PlainMessage<StreamPredictionsRequest> | undefined): boolean {
    return proto3.util.equals(StreamPredictionsRequest, a, b);
  }
}

/**
 * @generated from message aleph.nlp.v1.StreamPredictionsResponse
 */
export class StreamPredictionsResponse extends Message<StreamPredictionsResponse> {
  /**
   * @generated from field: string entity_id = 1;
   */
  entityId = "";

  /**
   * @generated from field: float probability = 2;
   */
  probability = 0;

  /**
   * @generated from field: string predicted_state = 3;
   */
  predictedState = "";

  /**
   * @generated from field: string explanation = 4;
   */
  explanation = "";

  constructor(data?: PartialMessage<StreamPredictionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.StreamPredictionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "probability", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "predicted_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "explanation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamPredictionsResponse {
    return new StreamPredictionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamPredictionsResponse {
    return new StreamPredictionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamPredictionsResponse {
    return new StreamPredictionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StreamPredictionsResponse | PlainMessage<StreamPredictionsResponse> | undefined, b: StreamPredictionsResponse | PlainMessage<StreamPredictionsResponse> | undefined): boolean {
    return proto3.util.equals(StreamPredictionsResponse, a, b);
  }
}

/**
 * @generated from message aleph.nlp.v1.AlephPrediction
 */
export class AlephPrediction extends Message<AlephPrediction> {
  /**
   * @generated from field: string entity_id = 1;
   */
  entityId = "";

  /**
   * @generated from field: float probability = 2;
   */
  probability = 0;

  /**
   * @generated from field: string predicted_state = 3;
   */
  predictedState = "";

  /**
   * es: "prophet", "polymarket"
   *
   * @generated from field: string model_source = 4;
   */
  modelSource = "";

  /**
   * @generated from field: string explanation = 5;
   */
  explanation = "";

  /**
   * @generated from field: int64 timestamp = 6;
   */
  timestamp = protoInt64.zero;

  constructor(data?: PartialMessage<AlephPrediction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aleph.nlp.v1.AlephPrediction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "probability", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "predicted_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "model_source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "explanation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AlephPrediction {
    return new AlephPrediction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AlephPrediction {
    return new AlephPrediction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AlephPrediction {
    return new AlephPrediction().fromJsonString(jsonString, options);
  }

  static equals(a: AlephPrediction | PlainMessage<AlephPrediction> | undefined, b: AlephPrediction | PlainMessage<AlephPrediction> | undefined): boolean {
    return proto3.util.equals(AlephPrediction, a, b);
  }
}

